#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# tests/certificate-identity/run.sh -- fixture tests for scripts/certificate-identity.sh:
#   * identity_file_list: the digested paths are exactly the expected set, sorted;
#   * identity_digest_lines: fails when a listed file is missing;
#   * _identity_check (--check): a current tree; a digests.txt whose digest lines do not hash to
#     its own identity line; a stale generated file (axioms.txt naming an old identity while
#     digests.txt is current); a NOT AUDITED axioms.txt; a STALE recheck.txt; a current-but-PARTIAL
#     recheck.txt; and an absent recheck.txt (a [skip], not a [FAIL]).
#   * version-scoping (cargo_version_normalized_sha256, via identity_digest_lines): a realistic
#     rust/Cargo.toml ([package] + one [dependencies] entry) and rust/Cargo.lock (the format
#     preamble, the root [[package]] block, and a second [[package]] block for a fabricated
#     dependency) -- bumping the root package's own version (in either file, or both) leaves the
#     tree identity unchanged; bumping the dependency's version, the lockfile format version, or
#     `edition`, or adding a new dependency, all change it.
#
# Builds a small throwaway tree per case: a repo root carrying the few optional nix/flake inputs
# identity_digest_lines reads via `../`, and a framed_channel/ directory holding its own copy of
# certificate-identity.sh (so _identity_check's module-level `_certificate_identity_ex` resolves
# inside the fixture, not the real repository) plus one dummy file per identity_file_list entry
# that is not found by a wildcard glob -- except rust/Cargo.toml and rust/Cargo.lock, which get
# realistic TOML-shaped content instead of a dummy, so the version-scoping cases have something to
# mutate.
#
# Usage: bash tests/certificate-identity/run.sh [-h | --help]      (from any directory)
# Requires: bash >= 4.4, coreutils (sha256sum), find.
# Exit: 0 every case behaves as recorded, 1 otherwise, 2 usage error.

set -u

case "${1:-}" in
  "") ;;
  -h|--help) awk 'NR > 2 && !/^#/ { exit } NR > 2 { sub(/^# ?/, ""); print }' "$0"; exit 0 ;;
  *) echo "run.sh: unknown argument '$1' (try --help)" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EX="$(cd "$HERE/../.." && pwd)"
REAL_CI="$EX/scripts/certificate-identity.sh"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

failures=0

# The fixed-path members of identity_file_list, beyond the wildcard-found *.rs/*.lean files.
FIXED_FILES=(
  aeneas/GenVectors.lean lean/FramedChannelChallenge.lean aeneas/FramedChannelAeneasChallenge.lean
  lean/lakefile.toml lean/lean-toolchain lean/lake-manifest.json
  aeneas/lakefile.toml aeneas/lean-toolchain aeneas/lake-manifest.json
  certificate/vectors.txt certificate/policy.txt certificate/candidates.txt
  check.sh scripts/refresh-hashes.sh scripts/refresh-vectors.sh scripts/refresh-extraction.sh
  scripts/lib/aeneas-revs.sh scripts/spec-check.sh scripts/refresh-candidates.sh
  scripts/lib/approval-digests.sh scripts/check-approvals.sh approve.sh
  scripts/comparator-configs.sh scripts/certificate-identity.sh scripts/check-spdx.sh
  scripts/lib/packages.sh
  recheck/lakefile.toml recheck/lean-toolchain recheck/lake-manifest.json
  scripts/lib/recheck-revs.sh
  recheck/landrun-shim.sh scripts/recheck-comparator.sh scripts/recheck-kernel.sh
  scripts/recheck-record.sh
)
# Sample wildcard-found members, one per glob clause in identity_file_list.
WILDCARD_FILES=(
  rust/Cargo.toml rust/Cargo.lock rust/src/lib.rs
  lean/FramedChannel/Foo.lean lean/FramedChannelChallenge/Foo.lean
  aeneas/FramedChannelAeneas/Foo.lean aeneas/FramedChannelAeneasChallenge/Foo.lean
)

# write_cargo_fixtures DIR -- realistic rust/Cargo.toml and rust/Cargo.lock content, replacing
# mk_tree's one-line dummy for these two paths: a [package] table with name/version/edition/
# rust-version and one [dependencies] entry, and a lockfile with the format preamble
# (`version = 4`), the root framed_channel [[package]] block, and a second [[package]] block for
# a fabricated dependency carrying its own name/version/source/checksum.
write_cargo_fixtures() {
  local dir="$1"
  cat > "$dir/rust/Cargo.toml" <<'EOF'
[package]
name = "framed_channel"
version = "0.1.0"
edition = "2021"
rust-version = "1.95.0"

[dependencies]
fixturedep = "1.0"
EOF
  cat > "$dir/rust/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "framed_channel"
version = "0.1.0"
dependencies = [
 "fixturedep",
]

[[package]]
name = "fixturedep"
version = "2.3.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
EOF
}

# mk_tree DIR -- a complete throwaway framed_channel/ tree: every identity_file_list member
# present (dummy content; only the paths matter, except rust/Cargo.toml and rust/Cargo.lock, which
# get write_cargo_fixtures' realistic content), plus a copy of certificate-identity.sh at the same
# scripts/ depth as the real repository so BASH_SOURCE-derived paths resolve inside DIR, and a copy
# of the real scripts/lib/approval-digests.sh over the dummy one (certificate-identity.sh sources
# it at module load; the copied script must source the real lib, not the one-line dummy).
mk_tree() {
  local dir="$1" f
  mkdir -p "$dir"
  for f in "${FIXED_FILES[@]}" "${WILDCARD_FILES[@]}"; do
    mkdir -p "$dir/$(dirname "$f")"
    echo "fixture $f" > "$dir/$f"
  done
  cp "$REAL_CI" "$dir/scripts/certificate-identity.sh"
  cp "$EX/scripts/lib/approval-digests.sh" "$dir/scripts/lib/approval-digests.sh"
  write_cargo_fixtures "$dir"
}

# tree_identity DIR -- echo the sha256:<hex> identity of DIR, computed via the throwaway copy.
tree_identity() {
  local dir="$1" lines
  lines="$(identity_digest_lines "$dir")" || return 1
  printf 'sha256:%s\n' "$(printf '%s\n' "$lines" | identity_of_lines)"
}

# write_certs DIR IDENTITY -- a current, mutually-consistent digests.txt/axioms.txt/ladder.txt/
# countermodels.txt naming IDENTITY (identity: sha256:<hex>, without the sha256: prefix duplicated
# -- IDENTITY already carries it stripped by the caller as needed).
write_certs() {
  local dir="$1" hex="$2" lines
  mkdir -p "$dir/certificate"
  lines="$(identity_digest_lines "$dir")" || return 1
  {
    echo "# framed_channel source digests (generated by check.sh; do not edit)"
    echo "# fixture"
    printf '%s\n' "$lines"
    echo "identity: sha256:$hex"
  } > "$dir/certificate/digests.txt"
  {
    echo "# framed_channel axiom audit (generated by check.sh; do not edit)"
    echo "lean: Lean (fixture)"
    echo "certificate identity: sha256:$hex"
    echo "trusted axioms: propext Classical.choice Quot.sound"
  } > "$dir/certificate/axioms.txt"
  {
    echo "# framed_channel proof ladder (generated by check.sh; do not edit)"
    echo "# certificate identity: sha256:$hex"
    echo "rung 1"
  } > "$dir/certificate/ladder.txt"
  {
    echo "# framed_channel refuted candidate statements (generated by check.sh; do not edit)"
    echo "# certificate identity: sha256:$hex"
  } > "$dir/certificate/countermodels.txt"
}

expect() {
  # expect NAME WANT_RC WANT_TEXT -- COMMAND...
  local name="$1" want_rc="$2" want_text="$3"
  shift 4
  local out rc
  out="$("$@" 2>&1)"
  rc=$?
  if [ "$rc" -eq "$want_rc" ] && { [ -z "$want_text" ] || grep -qF -- "$want_text" <<< "$out"; }; then
    echo "[ok] $name (exit $rc)"
  else
    echo "[FAIL] $name: exit $rc (expected $want_rc), text '$want_text'"
    sed 's/^/    /' <<< "$out"
    failures=$((failures + 1))
  fi
}

# ---------------------------------------------------------------------- identity_file_list
# shellcheck source=/dev/null
. "$REAL_CI"

tree="$work/base"
mk_tree "$tree"

expected="$work/expected-list"
{ printf '%s\n' "${FIXED_FILES[@]}" "${WILDCARD_FILES[@]}"; } | LC_ALL=C sort > "$expected"
actual="$(identity_file_list "$tree")"
if diff -u "$expected" <(printf '%s\n' "$actual") > "$work/list.diff"; then
  echo "[ok] identity_file_list: exactly the expected set, sorted"
else
  echo "[FAIL] identity_file_list: unexpected set"
  sed 's/^/    /' "$work/list.diff"
  failures=$((failures + 1))
fi

# A file that is present but does not match any glob or the fixed list must not appear.
echo not-listed > "$tree/rust/README.md"
if identity_file_list "$tree" | grep -qF 'rust/README.md'; then
  echo "[FAIL] identity_file_list: an unrelated rust/README.md was included"
  failures=$((failures + 1))
else
  echo "[ok] identity_file_list: an unrelated file is not included"
fi
rm -f "$tree/rust/README.md"

# ------------------------------------------------------------------- identity_digest_lines
missing_tree="$work/missing"
mk_tree "$missing_tree"
rm -f "$missing_tree/check.sh"
if identity_digest_lines "$missing_tree" > /dev/null 2>&1; then
  echo "[FAIL] identity_digest_lines: succeeded despite a missing listed file (check.sh)"
  failures=$((failures + 1))
else
  echo "[ok] identity_digest_lines: fails when a listed file (check.sh) is missing"
fi

# ---------------------------------------------------------------------------- _identity_check
# Each case sources its own copy of certificate-identity.sh so _certificate_identity_ex resolves
# to that case's directory (a fresh subshell per case keeps the sourced state isolated).
run_check() {
  local dir="$1"
  ( . "$dir/scripts/certificate-identity.sh" && _identity_check )
}

hex="$(tree_identity "$tree" | sed 's/^sha256://')"

# current tree: everything [ok], recheck.txt included and current+complete.
cur="$work/current"; mk_tree "$cur"
write_certs "$cur" "$hex"
mkdir -p "$cur/certificate"
{
  echo "# fixture recheck"
  echo "certificate identity: sha256:$hex"
  echo "produced on: fixture"
  echo "record: complete"
} > "$cur/certificate/recheck.txt"
expect "current tree: exit 0" 0 "certificate/recheck.txt names this tree" -- run_check "$cur"

# digests.txt whose digest lines do not hash to its own identity: line.
baddig="$work/baddigest"; mk_tree "$baddig"
write_certs "$baddig" "$hex"
sed -i "s/^identity: sha256:$hex\$/identity: sha256:0000000000000000000000000000000000000000000000000000000000000000/" "$baddig/certificate/digests.txt"
expect "digests.txt: digest lines do not hash to its identity line" 1 "its identity: line says" -- run_check "$baddig"

# a stale generated file: digests.txt current, axioms.txt names an old identity.
stale="$work/stale"; mk_tree "$stale"
write_certs "$stale" "$hex"
sed -i "s/^certificate identity: sha256:$hex\$/certificate identity: sha256:1111111111111111111111111111111111111111111111111111111111111111/" "$stale/certificate/axioms.txt"
expect "stale axioms.txt: names an old identity" 1 "certificate/axioms.txt is for identity" -- run_check "$stale"

# a NOT AUDITED axioms.txt: current identity, but carries the NOT AUDITED marker.
notaudited="$work/notaudited"; mk_tree "$notaudited"
write_certs "$notaudited" "$hex"
echo "NOT AUDITED: some-package" >> "$notaudited/certificate/axioms.txt"
expect "axioms.txt: NOT AUDITED package section" 1 "NOT AUDITED package section" -- run_check "$notaudited"

# a STALE recheck.txt: names an identity that is not this tree's.
staler="$work/stalerecheck"; mk_tree "$staler"
write_certs "$staler" "$hex"
{
  echo "# fixture recheck"
  echo "certificate identity: sha256:2222222222222222222222222222222222222222222222222222222222222222"
  echo "produced on: fixture"
  echo "record: complete"
} > "$staler/certificate/recheck.txt"
expect "recheck.txt: STALE (names a different identity)" 1 "STALE; rerun check.sh --recheck" -- run_check "$staler"

# a current-but-PARTIAL recheck.txt.
partial="$work/partialrecheck"; mk_tree "$partial"
write_certs "$partial" "$hex"
{
  echo "# fixture recheck"
  echo "certificate identity: sha256:$hex"
  echo "produced on: fixture"
  echo "record: partial (Comparator NOT-RUN)"
} > "$partial/certificate/recheck.txt"
expect "recheck.txt: current but not a complete record" 1 "is not a complete record" -- run_check "$partial"

# an absent recheck.txt: skip, not fail -- the run overall still succeeds.
absent="$work/absentrecheck"; mk_tree "$absent"
write_certs "$absent" "$hex"
expect "recheck.txt: absent is a [skip], overall exit 0" 0 "independent recheck NOT RUN" -- run_check "$absent"

# ------------------------------------------------------------------------ version-scoping cases
# A shared base tree with realistic Cargo fixtures (write_cargo_fixtures); each case works on its
# own copy so mutations never interact, and is compared against this base tree's identity.
verbase="$work/verbase"; mk_tree "$verbase"
verbase_identity="$(tree_identity "$verbase")"

# version_case NAME EXPECT(same|changed) MUTATE_FN : copy $verbase to a fresh case dir, run
# MUTATE_FN inside the copy, recompute the copy's identity, and compare against $verbase_identity
# per EXPECT.
version_case() {
  local name="$1" expect_mode="$2"; shift 2
  local casedir id
  casedir="$work/vercase-$(printf '%s' "$name" | tr -c 'a-zA-Z0-9' '_')"
  rm -rf "$casedir"
  cp -r "$verbase" "$casedir"
  ( cd "$casedir" && "$@" )
  id="$(tree_identity "$casedir")"
  if { [ "$expect_mode" = same ] && [ "$id" = "$verbase_identity" ]; } || \
     { [ "$expect_mode" = changed ] && [ "$id" != "$verbase_identity" ]; }; then
    echo "[ok] version-scoping: $name ($expect_mode)"
  else
    echo "[FAIL] version-scoping: $name: identity was $id, base was $verbase_identity (expected $expect_mode)"
    failures=$((failures + 1))
  fi
}

bump_toml_version() { sed -i 's/^version = "0.1.0"$/version = "8.8.8"/' rust/Cargo.toml; }
bump_lock_root_version() { sed -i 's/^version = "0.1.0"$/version = "8.8.8"/' rust/Cargo.lock; }
bump_both_root_versions() { bump_toml_version; bump_lock_root_version; }
bump_dependency_version() { sed -i 's/^version = "2.3.4"$/version = "2.3.5"/' rust/Cargo.lock; }
bump_lockfile_format_version() { sed -i 's/^version = 4$/version = 5/' rust/Cargo.lock; }
change_edition() { sed -i 's/^edition = "2021"$/edition = "2024"/' rust/Cargo.toml; }
add_dependency_entry() { sed -i '/^fixturedep = "1.0"$/a another = "2.0"' rust/Cargo.toml; }

version_case "bump root package version in Cargo.toml only" same bump_toml_version
version_case "bump root [[package]] version in Cargo.lock only" same bump_lock_root_version
version_case "bump root version in both Cargo.toml and Cargo.lock" same bump_both_root_versions
version_case "bump dependency (fixturedep) version in Cargo.lock" changed bump_dependency_version
version_case "bump lockfile format version (version = 4 -> 5)" changed bump_lockfile_format_version
version_case "change edition in Cargo.toml" changed change_edition
version_case "add a new [dependencies] entry to Cargo.toml" changed add_dependency_entry

# ------------------------------------------------------ cargo_version_normalized_sha256 refusals
# Direct unit cases for the transform's own refusal paths (not routed through identity_digest_lines).
out="$(cargo_version_normalized_sha256 "$verbase/rustfmt.toml" 2>&1)"
rc=$?
if [ "$rc" -eq 2 ] && [ -z "$out" ]; then
  echo "[ok] cargo_version_normalized_sha256: non-Cargo.* basename returns 2, prints nothing"
else
  echo "[FAIL] cargo_version_normalized_sha256: non-Cargo.* basename: exit $rc, output '$out' (expected exit 2, no output)"
  failures=$((failures + 1))
fi

out="$(cargo_version_normalized_sha256 "$verbase/rust/Cargo.lock" 2>&1)"
rc=$?
if [ "$rc" -eq 1 ] && [ -z "$out" ]; then
  echo "[ok] cargo_version_normalized_sha256: Cargo.lock with an empty ROOT_NAME prints nothing, returns 1"
else
  echo "[FAIL] cargo_version_normalized_sha256: Cargo.lock with an empty ROOT_NAME: exit $rc, output '$out' (expected exit 1, no output)"
  failures=$((failures + 1))
fi

out="$(cargo_version_normalized_sha256 "$verbase/rust/Cargo.lock" "no-such-package" 2>&1)"
rc=$?
if [ "$rc" -eq 1 ] && [ -z "$out" ]; then
  echo "[ok] cargo_version_normalized_sha256: Cargo.lock with an unresolvable ROOT_NAME prints nothing, returns 1"
else
  echo "[FAIL] cargo_version_normalized_sha256: Cargo.lock with an unresolvable ROOT_NAME: exit $rc, output '$out' (expected exit 1, no output)"
  failures=$((failures + 1))
fi

if [ "$failures" -eq 0 ]; then
  echo "certificate-identity: PASS"
  exit 0
fi
echo "certificate-identity: FAIL ($failures case(s))"
exit 1
