#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# check-spdx.sh -- verify every hand-written source file carries the license header. READ-ONLY.
#
# Every .rs .lean .sh .css .js .mjs .ts file must carry `SPDX-License-Identifier: Apache-2.0` in its
# first 3 lines, except the EXCLUDED paths below: the Aeneas-generated Lean files, which must keep
# their generator banner instead. LICENSE and NOTICE must exist at the root.
# Files come from `git ls-files --cached --others --exclude-standard` in a git work tree, otherwise
# from `find` with .lake, node_modules, dist, target and .git pruned. check.sh runs it.
#
# Usage: bash scripts/check-spdx.sh [--root DIR] [-h | --help]
#   --root DIR   the tree to scan (default: the repository root, the parent of framed_channel/)
#
# Requires: bash >= 4.4; git (optional).
# Exit: 0 every check passes, 1 a header, banner, LICENSE or NOTICE is missing, 2 usage error.

set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --root)
      [ "$#" -ge 2 ] || { echo "check-spdx.sh: --root needs a directory" >&2; exit 2; }
      ROOT="$2"; shift 2 ;;
    -h|--help) awk 'NR > 2 && !/^#/ { exit } NR > 2 { sub(/^# ?/, ""); print }' "$0"; exit 0 ;;
    *) echo "check-spdx.sh: unknown argument '$1' (expected --root DIR)" >&2
       exit 2 ;;
  esac
done
[ -d "$ROOT" ] || { echo "check-spdx.sh: --root '$ROOT' is not a directory" >&2; exit 2; }
ROOT="$(cd "$ROOT" && pwd)"

# path (relative to ROOT)|reason|check ("banner" re-verifies the generator banner, "none" checks
# nothing beyond exclusion)
EXCLUDED=(
  "framed_channel/aeneas/FramedChannelAeneas/Extracted/Types.lean|generated by refresh-extraction.sh (Aeneas)|banner"
  "framed_channel/aeneas/FramedChannelAeneas/Extracted/Funs.lean|generated by refresh-extraction.sh (Aeneas)|banner"
)
GENERATED_BANNER="THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS"

# excluded_check_for PATH: print the check of an EXCLUDED path; fail when PATH is not excluded.
excluded_check_for() {
  local p="$1" entry epath echeck
  for entry in "${EXCLUDED[@]}"; do
    IFS='|' read -r epath _ echeck <<< "$entry"
    if [ "$p" = "$epath" ]; then printf '%s\n' "$echeck"; return 0; fi
  done
  return 1
}

is_pruned() {
  case "$1" in
    .lake/*|*/.lake/*|node_modules/*|*/node_modules/*|dist/*|*/dist/*|target/*|*/target/*|.git/*|*/.git/*) return 0 ;;
    *) return 1 ;;
  esac
}

candidates_file="$(mktemp)"
trap 'rm -f "$candidates_file"' EXIT

if git -C "$ROOT" rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  git -C "$ROOT" ls-files --cached --others --exclude-standard > "$candidates_file"
else
  find "$ROOT" \
    \( -name .lake -o -name node_modules -o -name dist -o -name target -o -name .git \) -prune -o \
    -type f -print \
  | sed "s|^$ROOT/||" > "$candidates_file"
fi

status=0
checked=0
excluded_count=0
while IFS= read -r rel; do
  [ -n "$rel" ] || continue
  case "$rel" in
    *.rs|*.lean|*.sh|*.css|*.js|*.mjs|*.ts) ;;
    *) continue ;;
  esac
  is_pruned "$rel" && continue

  abs="$ROOT/$rel"
  [ -f "$abs" ] || continue

  if echk="$(excluded_check_for "$rel")"; then
    excluded_count=$((excluded_count + 1))
    if [ "$echk" = banner ]; then
      if ! head -3 "$abs" | grep -qF "$GENERATED_BANNER"; then
        echo "[FAIL] $rel: generated file has lost its generator banner"
        status=1
      fi
    fi
    continue
  fi

  checked=$((checked + 1))
  if ! head -3 "$abs" | grep -q 'SPDX-License-Identifier: Apache-2.0'; then
    echo "[FAIL] $rel: no SPDX-License-Identifier: Apache-2.0 header in the first 3 lines"
    status=1
  fi
done < "$candidates_file"

for f in LICENSE NOTICE; do
  if [ ! -f "$ROOT/$f" ]; then
    echo "[FAIL] $f: missing at the repository root"
    status=1
  fi
done

if [ "$status" -eq 0 ]; then
  echo "[ok] license headers ($checked files, $excluded_count excluded)"
fi
exit "$status"
