-- SPDX-License-Identifier: Apache-2.0
import Lean

/-!
# SpecCheck: purity, statement hashes and closure digests of the Challenge libraries

The Lean half of the gate's Specify checks. It is run by `../../scripts/spec-check.sh` in an environment
that imports one package's statement-only Challenge library (`FramedChannelChallenge` for the core
package, `FramedChannelAeneasChallenge` for the bridge) and this module, and it prints one record
per line:

* `IMPURE <name> <kind>` -- a constant declared in a Challenge module that is neither a theorem
  whose proof is `sorry` nor an auxiliary generated by such a theorem (a name extending a Challenge
  theorem's name, such as a statement-local `match_1`). A Challenge module may hold statements
  only: no definition, axiom, opaque constant, non-`Prop` instance, macro or elaborator.
* `stmt <name> <hash> <module>` -- per Challenge theorem, the structural hash of its elaborated
  statement, the same `hash info.type` `Certify.lean`'s `stmt_hash%` computes for the registry
  column, and the Challenge module that restates it (the approval unit that owns the statement).
* `digest <module> <nat>` -- per Challenge module that declares a theorem, a digest of what an
  approval of that module covers: the module's (theorem name, statement hash) pairs, followed by
  every constant in the transitive closure of those statements, walked as Comparator walks it. A
  Challenge theorem met in the walk contributes its statement only; every other constant
  contributes its name, kind, universe parameters, type hash and, for a definition, theorem or
  opaque constant, its value hash, and for an inductive type, constructor or recursor, its shape.
  So the digest changes when a statement changes, and when any definition, extracted function,
  library definition or proof term embedded in the statements' closure changes; it ignores
  comments, docstrings and source positions, which are not part of a constant.
* `reached <name>` -- every definition of `FramedChannelAeneas.Extracted.Funs` (the Aeneas
  extraction) in the union of all statement closures, compiler auxiliaries excluded. The selection
  check compares this set with the Select candidates.
* `defs-thm <name>` -- every user-declared theorem of a definitions module (a module of this
  example whose last name component is `Defs` or ends in `Defs`; structure field projections
  excluded): the proofs that live inside the specification's trusted imports, checked against the
  `shared-proof` rows of `certificate/policy.txt`.
* `closure-thm <name>` -- every user-declared theorem of this example that is not a Challenge
  theorem but lies in some statement's closure: a proof the specification depends on. The gate
  requires each to be a `shared-proof` row, which also detects a statement of one package that
  mentions a registered theorem of the other.

Scope, stated as the registry's statement hash states it: every hash here is a 64-bit structural
`Expr` hash and the digest a `mixHash` fold over them. That is a change detector bound to this
toolchain, not a cryptographic commitment: a Lean, Aeneas or Mathlib bump changes the digests and
so requires re-approval. Comparator's own run is the exact check. Output is sorted and
deterministic.

This module declares no theorem and carries no `#print axioms`: it is tooling, audited by the
build like every module of the core package, and nothing in the proofs or registries imports it.
-/

namespace FramedChannel.SpecCheck

open Lean Elab Command

/-- The module a constant was declared in, or `none` for the current file. -/
def moduleOf (env : Environment) (n : Name) : Option Name :=
  (env.getModuleIdxFor? n).map fun i => env.header.moduleNames[i.toNat]!

/-- `true` when `m` is `root` or a module below it. -/
def underRoot (root m : Name) : Bool :=
  root == m || root.isPrefixOf m

/-- A definitions module of this example: a module of the `FramedChannel` or `FramedChannelAeneas`
library whose last name component is `Defs`. The test is exact, not a suffix test: every unit
lives in a `<Layer>/<Unit>/` directory whose definitions module is `Defs.lean`, so no module
needs `...Defs` glued onto a unit name, and a suffix test would silently admit a future
`FooDefs` that the layout rule forbids. -/
def isDefsModule (m : Name) : Bool :=
  ((`FramedChannel).isPrefixOf m || (`FramedChannelAeneas).isPrefixOf m) &&
    match m with
    | .str _ s => s == "Defs"
    | _ => false

/-- The kind of a constant, as printed. -/
def kindOf : ConstantInfo → String
  | .axiomInfo _ => "axiom"
  | .defnInfo _ => "def"
  | .thmInfo _ => "theorem"
  | .opaqueInfo _ => "opaque"
  | .quotInfo _ => "quot"
  | .inductInfo _ => "inductive"
  | .ctorInfo _ => "constructor"
  | .recInfo _ => "recursor"

/-- `e` with its leading lambdas removed. -/
partial def stripLambdas : Expr → Expr
  | .lam _ _ b _ => stripLambdas b
  | .mdata _ b => stripLambdas b
  | e => e

/-- A theorem whose proof is exactly `sorry` (under the binders of its statement). -/
def isSorryTheorem : ConstantInfo → Bool
  | .thmInfo t => (stripLambdas t.value).getAppFn.isConstOf ``sorryAx
  | _ => false

/-- A compiler-generated auxiliary that is not part of a declaration's identity. -/
def isAuxName (n : Name) : Bool :=
  n.components.any fun c =>
    match c with
    | .str _ s => s.startsWith "_" || s.startsWith "match_" || s.startsWith "proof_" ||
        s == "eq_def" || s.startsWith "eq_" || s == "injEq" || s == "inj" || s == "sizeOf_spec" ||
        s == "noConfusion" || s == "noConfusionType"
    | .num _ _ => true
    | _ => false

/-- Fold a string into a hash. -/
def mixStr (h : UInt64) (s : String) : UInt64 := mixHash h (hash s)

/-- Fold a name into a hash, by its string form. -/
def mixName (h : UInt64) (n : Name) : UInt64 := mixStr h n.toString

/-- The shape-and-content hash of one closure constant. Targets contribute their statement only. -/
def constHash (targets : NameSet) (n : Name) (ci : ConstantInfo) : UInt64 := Id.run do
  let mut h := mixName 7 n
  h := mixStr h (kindOf ci)
  for u in ci.levelParams do
    h := mixName h u
  h := mixHash h (hash ci.type)
  if targets.contains n then
    return h
  match ci with
  | .defnInfo d => h := mixHash h (hash d.value)
  | .thmInfo t => h := mixHash h (hash t.value)
  | .opaqueInfo o => h := mixHash h (hash o.value)
  | .inductInfo i =>
    h := mixHash h (hash i.numParams); h := mixHash h (hash i.numIndices)
    for c in i.ctors do h := mixName h c
    for a in i.all do h := mixName h a
    h := mixHash h (hash i.isRec)
  | .ctorInfo c =>
    h := mixName h c.induct; h := mixHash h (hash c.cidx)
    h := mixHash h (hash c.numParams); h := mixHash h (hash c.numFields)
  | .recInfo r =>
    h := mixHash h (hash r.numParams); h := mixHash h (hash r.numIndices)
    h := mixHash h (hash r.numMotives); h := mixHash h (hash r.numMinors)
    for rule in r.rules do
      h := mixName h rule.ctor; h := mixHash h (hash rule.nfields); h := mixHash h (hash rule.rhs)
  | _ => pure ()
  return h

/-- Comparator's closure walk: from the statements of `start`, follow every constant used; a target
contributes its type only, every other constant its type and value, and an inductive family its
constructors (and a constructor or recursor its inductive). -/
partial def closureOf (env : Environment) (targets : NameSet) (start : Array Name) : NameSet :=
  Id.run do
    let mut work : Array Name := #[]
    for s in start do
      if let some ci := env.find? s then
        work := work ++ ci.type.getUsedConstants
    let mut seen : NameSet := {}
    while !work.isEmpty do
      let n := work.back!
      work := work.pop
      if seen.contains n then continue
      seen := seen.insert n
      match env.find? n with
      | none => pure ()
      | some ci =>
        let used :=
          if targets.contains n then ci.type.getUsedConstants
          else ci.type.getUsedConstants ++
            (match ci.value? (allowOpaque := true) with
             | some v => v.getUsedConstants
             | none => #[])
        let extra : Array Name := match ci with
          | .inductInfo i => i.ctors.toArray
          | .ctorInfo c => #[c.induct]
          | .recInfo r => #[r.getMajorInduct]
          | _ => #[]
        work := work ++ used ++ extra
    return seen

/-- Sort names by their string form. -/
def sortNames (ns : Array Name) : Array Name :=
  ns.qsort fun a b => a.toString < b.toString

/-- `#spec_check Root`: print the records described in the module docstring for the Challenge
library rooted at `Root`. -/
elab "#spec_check " root:ident : command => do
  let env ← getEnv
  let root := root.getId
  let challengeMods := env.header.moduleNames.filter (underRoot root)
  if challengeMods.isEmpty then
    throwError "spec_check: no module under {root} is imported"
  -- Constants declared in Challenge modules, and the Challenge theorems among them.
  let mut declared : Array (Name × ConstantInfo) := #[]
  for (n, ci) in env.constants.map₁.toList do
    if let some m := moduleOf env n then
      if underRoot root m then
        declared := declared.push (n, ci)
  let theorems := declared.filter (fun (_, ci) => isSorryTheorem ci) |>.map (·.1)
  let targets : NameSet := theorems.foldl (·.insert ·) {}
  let mut lines : Array String := #[]
  -- (a) purity
  for (n, ci) in declared do
    if isSorryTheorem ci then continue
    let auxOfTheorem := theorems.any fun t => t.isPrefixOf n && t != n
    unless auxOfTheorem do
      lines := lines.push s!"IMPURE {n} {kindOf ci}"
  -- a Challenge theorem with no statement-only proof is caught above; so is a macro or elaborator,
  -- whose declarations are definitions
  -- (b) statement hashes
  for t in sortNames theorems do
    let some ci := env.find? t | continue
    let m := (moduleOf env t).getD .anonymous
    lines := lines.push s!"stmt {t} {hash ci.type} {m}"
  -- (c) per-module digests
  for m in sortNames challengeMods do
    let own := sortNames (theorems.filter fun t => moduleOf env t == some m)
    -- the library root imports the component modules and declares nothing: no approval unit
    if own.isEmpty then continue
    let mut h : UInt64 := mixName 11 m
    for t in own do
      let some ci := env.find? t | continue
      h := mixHash (mixName h t) (hash ci.type)
    let clos := closureOf env targets own
    let closNames := sortNames (clos.toList.toArray.filter fun n => !(own.contains n))
    for n in closNames do
      if let some ci := env.find? n then
        h := mixHash h (constHash targets n ci)
    lines := lines.push s!"digest {m} {h.toNat}"
  -- (d) extracted definitions reached by any statement
  let all := closureOf env targets theorems
  for n in sortNames all.toList.toArray do
    if moduleOf env n == some `FramedChannelAeneas.Extracted.Funs && !isAuxName n then
      if let some (.defnInfo _) := env.find? n then
        lines := lines.push s!"reached {n}"
  -- (e) user-declared theorems inside definitions modules
  let mut defsThms : Array Name := #[]
  for (n, ci) in env.constants.map₁.toList do
    if let some m := moduleOf env n then
      if isDefsModule m && !isAuxName n && !(env.getProjectionFnInfo? n).isSome then
        if let .thmInfo _ := ci then
          if (← findDeclarationRanges? n).isSome then
            defsThms := defsThms.push n
  for n in sortNames defsThms do
    lines := lines.push s!"defs-thm {n}"
  -- (f) theorems of this example that the statements depend on
  for n in sortNames all.toList.toArray do
    if targets.contains n || isAuxName n then continue
    let some (.thmInfo _) := env.find? n | continue
    let some m := moduleOf env n | continue
    unless (`FramedChannel).isPrefixOf m || (`FramedChannelAeneas).isPrefixOf m do continue
    if (env.getProjectionFnInfo? n).isSome then continue
    if (← findDeclarationRanges? n).isSome then
      lines := lines.push s!"closure-thm {n}"
  for l in lines do
    IO.println l

end FramedChannel.SpecCheck
