#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# tests/cert-freshness/run.sh -- fixture tests for scripts/certificate-freshness.sh.
#
# Each case commits a small framed_channel/certificate/ into a throwaway git repository, rewrites
# it the way a gate run on some host would, and checks the verdict of the strict comparison (the
# x86_64-linux gate) and of --portable-host (every other host). The last case reads the real
# committed axioms.txt, so a change to the shape of its `lean:` line that would silently turn
# --portable-host back into a strict comparison fails here rather than on an aarch64 runner.
#
# Usage: bash tests/cert-freshness/run.sh [-h | --help]      (from any directory)
# Requires: bash, git, sed, diff.
# Exit: 0 every case behaves as recorded, 1 otherwise, 2 usage error.

set -u

case "${1:-}" in
  "") ;;
  -h|--help) awk 'NR > 2 && !/^#/ { exit } NR > 2 { sub(/^# ?/, ""); print }' "$0"; exit 0 ;;
  *) echo "run.sh: unknown argument '$1' (try --help)" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EX="$(cd "$HERE/../.." && pwd)"
CHECK="$EX/scripts/certificate-freshness.sh"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

failures=0

X86='lean: Lean (version 4.31.0, x86_64-unknown-linux-gnu, commit 68218e876d2a38b1985b8590fff244a83c321783, Release)'
ARM='lean: Lean (version 4.31.0, aarch64-unknown-linux-gnu, commit 68218e876d2a38b1985b8590fff244a83c321783, Release)'
MAC='lean: Lean (version 4.31.0, arm64-apple-darwin24.6.0, commit 68218e876d2a38b1985b8590fff244a83c321783, Release)'

write_axioms() {
  # write_axioms FILE LEAN_LINE [AXIOMS]
  {
    echo "# framed_channel axiom audit (generated by check.sh; do not edit)"
    echo "$2"
    echo "certificate identity: sha256:0000000000000000000000000000000000000000000000000000000000000000"
    echo "trusted axioms: ${3:-propext Classical.choice Quot.sound}"
  } > "$1"
}

# new_repo DIR -- a committed certificate as the x86_64-linux gate writes it.
new_repo() {
  local d="$1"
  mkdir -p "$d/framed_channel/certificate"
  git -C "$d" init -q
  write_axioms "$d/framed_channel/certificate/axioms.txt" "$X86"
  printf 'rung 1\n' > "$d/framed_channel/certificate/ladder.txt"
  git -C "$d" add framed_channel/certificate/axioms.txt framed_channel/certificate/ladder.txt
  git -C "$d" -c user.name=fixture -c user.email=fixture@example.invalid commit -q -m fixture
}

expect() {
  # expect NAME WANT_RC WANT_TEXT -- ARGS...
  local name="$1" want_rc="$2" want_text="$3"
  shift 4
  local out rc
  out="$(bash "$CHECK" "$@" 2>&1)"
  rc=$?
  if [ "$rc" -eq "$want_rc" ] && { [ -z "$want_text" ] || grep -qF -- "$want_text" <<< "$out"; }; then
    echo "[ok] $name (exit $rc)"
  else
    echo "[FAIL] $name: exit $rc (expected $want_rc), text '$want_text'"
    sed 's/^/    /' <<< "$out"
    failures=$((failures + 1))
  fi
}

r="$work/clean"; new_repo "$r"
expect "unchanged certificate, strict" 0 "certificate fresh" -- --repo "$r"
expect "unchanged certificate, portable" 0 "certificate fresh" -- --repo "$r" --portable-host

r="$work/arm"; new_repo "$r"
write_axioms "$r/framed_channel/certificate/axioms.txt" "$ARM"
expect "aarch64-linux triple only, strict fails" 1 "stale certificate" -- --repo "$r"
expect "aarch64-linux triple only, portable passes" 0 "only in the target triple" -- --repo "$r" --portable-host

r="$work/mac"; new_repo "$r"
write_axioms "$r/framed_channel/certificate/axioms.txt" "$MAC"
expect "aarch64-darwin triple only, portable passes" 0 "only in the target triple" -- --repo "$r" --portable-host

r="$work/arm-and-axiom"; new_repo "$r"
write_axioms "$r/framed_channel/certificate/axioms.txt" "$ARM" "propext Classical.choice Quot.sound sorryAx"
expect "triple and an axiom line, portable fails" 1 "sorryAx" -- --repo "$r" --portable-host

r="$work/lean-version"; new_repo "$r"
write_axioms "$r/framed_channel/certificate/axioms.txt" "${ARM/4.31.0/4.32.0}"
expect "a different Lean version is not host-dependent" 1 "stale certificate" -- --repo "$r" --portable-host

r="$work/lean-commit"; new_repo "$r"
write_axioms "$r/framed_channel/certificate/axioms.txt" "${ARM/68218e87/00000000}"
expect "a different Lean commit is not host-dependent" 1 "stale certificate" -- --repo "$r" --portable-host

r="$work/other-file"; new_repo "$r"
write_axioms "$r/framed_channel/certificate/axioms.txt" "$ARM"
printf 'rung 2\n' > "$r/framed_channel/certificate/ladder.txt"
expect "triple plus another stale file, portable fails" 1 "ladder.txt" -- --repo "$r" --portable-host

r="$work/odd-shape"; new_repo "$r"
write_axioms "$r/framed_channel/certificate/axioms.txt" "lean: some other banner on aarch64"
expect "an unrecognised lean: line is compared strictly" 1 "stale certificate" -- --repo "$r" --portable-host

expect "not a git work tree" 2 "not a git work tree" -- --repo "$work"
expect "unknown argument" 2 "unknown argument" -- --bogus

# The committed axioms.txt must still have the shape --portable-host blanks.
real="$EX/certificate/axioms.txt"
if sed -E 's/^(lean: Lean \(version [^,]+, )[^,]+(, commit [0-9a-f]+, )/\1<target-triple>\2/' "$real" \
    | grep -q '^lean: Lean (version [^,]*, <target-triple>, commit '; then
  echo "[ok] the committed axioms.txt has the lean: line shape --portable-host blanks"
else
  echo "[FAIL] the committed axioms.txt's lean: line no longer has the shape --portable-host blanks:"
  sed -n 's/^lean: /    lean: /p' "$real"
  failures=$((failures + 1))
fi

if [ "$failures" -eq 0 ]; then
  echo "cert-freshness: PASS"
  exit 0
fi
echo "cert-freshness: FAIL ($failures case(s))"
exit 1
