-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [framed_channel]: function definitions
import Aeneas
import FramedChannelAeneas.Extracted.Types
import FramedChannelAeneas.Extracted.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace framed_channel

/-- Trait implementation: [alloc::vec::{impl core::default::Default for alloc::vec::Vec<T>}]
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 4413:0-4413:32
    Name pattern: [core::default::Default<alloc::vec::Vec<@T>>] -/
@[reducible, rust_trait_impl "core::default::Default<alloc::vec::Vec<@T>>"]
def alloc.vec.Vec.Insts.CoreDefaultDefault (T : Type) : core.default.Default
  (alloc.vec.Vec T) := {
  default := alloc.vec.Vec.Insts.CoreDefaultDefault.default T
}

/-- [framed_channel::channel::MARKER]
    Source: 'src/channel.rs', lines 29:0-29:28
    Visibility: public -/
@[global_simps, irreducible] def channel.MARKER : Std.U8 := 126#u8

/-- [framed_channel::channel::{impl core::fmt::Debug for framed_channel::channel::DeliverFail}::fmt]:
    Source: 'src/channel.rs', lines 37:9-37:14
    Visibility: public -/
def channel.DeliverFail.Insts.CoreFmtDebug.fmt
  (self : channel.DeliverFail) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "DeliverFail")

/-- Trait implementation: [framed_channel::channel::{impl core::fmt::Debug for framed_channel::channel::DeliverFail}]
    Source: 'src/channel.rs', lines 37:9-37:14 -/
@[reducible]
def channel.DeliverFail.Insts.CoreFmtDebug : core.fmt.Debug channel.DeliverFail
  := {
  fmt := channel.DeliverFail.Insts.CoreFmtDebug.fmt
}

/-- [framed_channel::channel::{impl core::clone::Clone for framed_channel::channel::DeliverFail}::clone]:
    Source: 'src/channel.rs', lines 37:16-37:21
    Visibility: public -/
def channel.DeliverFail.Insts.CoreCloneClone.clone
  (self : channel.DeliverFail) : Result channel.DeliverFail := do
  ok self

/-- Trait implementation: [framed_channel::channel::{impl core::clone::Clone for framed_channel::channel::DeliverFail}]
    Source: 'src/channel.rs', lines 37:16-37:21 -/
@[reducible]
def channel.DeliverFail.Insts.CoreCloneClone : core.clone.Clone
  channel.DeliverFail := {
  clone := channel.DeliverFail.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [framed_channel::channel::{impl core::marker::Copy for framed_channel::channel::DeliverFail}]
    Source: 'src/channel.rs', lines 37:23-37:27 -/
@[reducible]
def channel.DeliverFail.Insts.CoreMarkerCopy : core.marker.Copy
  channel.DeliverFail := {
  cloneInst := channel.DeliverFail.Insts.CoreCloneClone
}

/-- Trait implementation: [framed_channel::channel::{impl core::marker::StructuralPartialEq for framed_channel::channel::DeliverFail}]
    Source: 'src/channel.rs', lines 37:29-37:38 -/
@[reducible]
def channel.DeliverFail.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq channel.DeliverFail := {
}

/-- [framed_channel::channel::{impl core::cmp::PartialEq<framed_channel::channel::DeliverFail> for framed_channel::channel::DeliverFail}::eq]:
    Source: 'src/channel.rs', lines 37:29-37:38
    Visibility: public -/
def channel.DeliverFail.Insts.CoreCmpPartialEqDeliverFail.eq
  (self : channel.DeliverFail) (other : channel.DeliverFail) :
  Result Bool
  := do
  ok true

/-- Trait implementation: [framed_channel::channel::{impl core::cmp::PartialEq<framed_channel::channel::DeliverFail> for framed_channel::channel::DeliverFail}]
    Source: 'src/channel.rs', lines 37:29-37:38 -/
@[reducible]
def channel.DeliverFail.Insts.CoreCmpPartialEqDeliverFail : core.cmp.PartialEq
  channel.DeliverFail channel.DeliverFail := {
  eq := channel.DeliverFail.Insts.CoreCmpPartialEqDeliverFail.eq
}

/-- [framed_channel::channel::{impl core::cmp::Eq for framed_channel::channel::DeliverFail}::assert_fields_are_eq]:
    Source: 'src/channel.rs', lines 37:40-37:42
    Visibility: public -/
def channel.DeliverFail.Insts.CoreCmpEq.assert_fields_are_eq
  (self : channel.DeliverFail) : Result Unit := do
  ok ()

/-- Trait implementation: [framed_channel::channel::{impl core::cmp::Eq for framed_channel::channel::DeliverFail}]
    Source: 'src/channel.rs', lines 37:40-37:42 -/
@[reducible]
def channel.DeliverFail.Insts.CoreCmpEq : core.cmp.Eq channel.DeliverFail := {
  partialEqInst := channel.DeliverFail.Insts.CoreCmpPartialEqDeliverFail
  assert_fields_are_eq :=
    channel.DeliverFail.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [framed_channel::channel::{impl core::fmt::Debug for framed_channel::channel::SendFail}::fmt]:
    Source: 'src/channel.rs', lines 44:9-44:14
    Visibility: public -/
def channel.SendFail.Insts.CoreFmtDebug.fmt
  (self : channel.SendFail) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "SendFail")

/-- Trait implementation: [framed_channel::channel::{impl core::fmt::Debug for framed_channel::channel::SendFail}]
    Source: 'src/channel.rs', lines 44:9-44:14 -/
@[reducible]
def channel.SendFail.Insts.CoreFmtDebug : core.fmt.Debug channel.SendFail := {
  fmt := channel.SendFail.Insts.CoreFmtDebug.fmt
}

/-- [framed_channel::channel::{impl core::clone::Clone for framed_channel::channel::SendFail}::clone]:
    Source: 'src/channel.rs', lines 44:16-44:21
    Visibility: public -/
def channel.SendFail.Insts.CoreCloneClone.clone
  (self : channel.SendFail) : Result channel.SendFail := do
  ok self

/-- Trait implementation: [framed_channel::channel::{impl core::clone::Clone for framed_channel::channel::SendFail}]
    Source: 'src/channel.rs', lines 44:16-44:21 -/
@[reducible]
def channel.SendFail.Insts.CoreCloneClone : core.clone.Clone channel.SendFail
  := {
  clone := channel.SendFail.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [framed_channel::channel::{impl core::marker::Copy for framed_channel::channel::SendFail}]
    Source: 'src/channel.rs', lines 44:23-44:27 -/
@[reducible]
def channel.SendFail.Insts.CoreMarkerCopy : core.marker.Copy channel.SendFail
  := {
  cloneInst := channel.SendFail.Insts.CoreCloneClone
}

/-- Trait implementation: [framed_channel::channel::{impl core::marker::StructuralPartialEq for framed_channel::channel::SendFail}]
    Source: 'src/channel.rs', lines 44:29-44:38 -/
@[reducible]
def channel.SendFail.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq channel.SendFail := {
}

/-- [framed_channel::channel::{impl core::cmp::PartialEq<framed_channel::channel::SendFail> for framed_channel::channel::SendFail}::eq]:
    Source: 'src/channel.rs', lines 44:29-44:38
    Visibility: public -/
def channel.SendFail.Insts.CoreCmpPartialEqSendFail.eq
  (self : channel.SendFail) (other : channel.SendFail) : Result Bool := do
  ok true

/-- Trait implementation: [framed_channel::channel::{impl core::cmp::PartialEq<framed_channel::channel::SendFail> for framed_channel::channel::SendFail}]
    Source: 'src/channel.rs', lines 44:29-44:38 -/
@[reducible]
def channel.SendFail.Insts.CoreCmpPartialEqSendFail : core.cmp.PartialEq
  channel.SendFail channel.SendFail := {
  eq := channel.SendFail.Insts.CoreCmpPartialEqSendFail.eq
}

/-- [framed_channel::channel::{impl core::cmp::Eq for framed_channel::channel::SendFail}::assert_fields_are_eq]:
    Source: 'src/channel.rs', lines 44:40-44:42
    Visibility: public -/
def channel.SendFail.Insts.CoreCmpEq.assert_fields_are_eq
  (self : channel.SendFail) : Result Unit := do
  ok ()

/-- Trait implementation: [framed_channel::channel::{impl core::cmp::Eq for framed_channel::channel::SendFail}]
    Source: 'src/channel.rs', lines 44:40-44:42 -/
@[reducible]
def channel.SendFail.Insts.CoreCmpEq : core.cmp.Eq channel.SendFail := {
  partialEqInst := channel.SendFail.Insts.CoreCmpPartialEqSendFail
  assert_fields_are_eq := channel.SendFail.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [framed_channel::varint::encode_u32]: loop body 0:
    Source: 'src/varint.rs', lines 18:4-27:1
    Visibility: public -/
@[rust_loop_body]
def varint.encode_u32_loop.body
  (iter : core.ops.range.Range Std.I32) (n : Std.U32)
  (out : alloc.vec.Vec Std.U8) :
  Result (ControlFlow ((core.ops.range.Range Std.I32) × Std.U32 ×
    (alloc.vec.Vec Std.U8)) (alloc.vec.Vec Std.U8))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepI32 iter
  match o with
  | none => ok (done out)
  | some _ =>
    let i ← lift (n &&& 127#u32)
    let group ← lift (UScalar.cast .U8 i)
    let n1 ← n >>> 7#i32
    if n1 = 0#u32
    then let out1 ← alloc.vec.Vec.push out group
         ok (done out1)
    else
      let i1 ← lift (group ||| 128#u8)
      let out1 ← alloc.vec.Vec.push out i1
      ok (cont (iter1, n1, out1))

/-- [framed_channel::varint::encode_u32]: loop 0:
    Source: 'src/varint.rs', lines 18:4-27:1
    Visibility: public -/
@[rust_loop]
def varint.encode_u32_loop
  (iter : core.ops.range.Range Std.I32) (n : Std.U32)
  (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (iter1, n1, out1) => varint.encode_u32_loop.body iter1 n1 out1)
    (iter, n, out)

/-- [framed_channel::varint::encode_u32]:
    Source: 'src/varint.rs', lines 17:0-27:1
    Visibility: public -/
@[reducible]
def varint.encode_u32
  (n : Std.U32) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  varint.encode_u32_loop { start := 0#i32, «end» := 5#i32 } n out

/-- [framed_channel::crc8::POLY]
    Source: 'src/crc8.rs', lines 8:0-8:26
    Visibility: public -/
@[global_simps, irreducible] def crc8.POLY : Std.U8 := 7#u8

/-- [framed_channel::crc8::crc8]: loop body 1:
    Source: 'src/crc8.rs', lines 17:8-19:9
    Visibility: public -/
@[rust_loop_body]
def crc8.crc8_loop0_loop0.body
  (iter : core.ops.range.Range Std.I32) (crc : Std.U8) :
  Result (ControlFlow ((core.ops.range.Range Std.I32) × Std.U8) Std.U8)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepI32 iter
  match o with
  | none => ok (done crc)
  | some _ =>
    let i ← lift (crc &&& 128#u8)
    if i != 0#u8
    then
      let i1 ← crc <<< 1#i32
      let crc1 ← lift (i1 ^^^ crc8.POLY)
      ok (cont (iter1, crc1))
    else let crc1 ← crc <<< 1#i32
         ok (cont (iter1, crc1))

/-- [framed_channel::crc8::crc8]: loop 1:
    Source: 'src/crc8.rs', lines 17:8-19:9
    Visibility: public -/
@[rust_loop]
def crc8.crc8_loop0_loop0
  (iter : core.ops.range.Range Std.I32) (crc : Std.U8) : Result Std.U8 := do
  loop
    (fun (iter1, crc1) => crc8.crc8_loop0_loop0.body iter1 crc1)
    (iter, crc)

/-- [framed_channel::crc8::crc8]: loop body 0:
    Source: 'src/crc8.rs', lines 15:4-20:5
    Visibility: public -/
@[rust_loop_body]
def crc8.crc8_loop0.body
  (iter : core.slice.iter.Iter Std.U8) (crc : Std.U8) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U8) × Std.U8) Std.U8)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done crc)
  | some b =>
    let crc1 ← lift (crc ^^^ b)
    let crc2 ←
      crc8.crc8_loop0_loop0 { start := 0#i32, «end» := 8#i32 } crc1
    ok (cont (iter1, crc2))

/-- [framed_channel::crc8::crc8]: loop 0:
    Source: 'src/crc8.rs', lines 15:4-20:5
    Visibility: public -/
@[rust_loop]
def crc8.crc8_loop0
  (iter : core.slice.iter.Iter Std.U8) (crc : Std.U8) : Result Std.U8 := do
  loop
    (fun (iter1, crc1) => crc8.crc8_loop0.body iter1 crc1)
    (iter, crc)

/-- [framed_channel::crc8::crc8]:
    Source: 'src/crc8.rs', lines 13:0-22:1
    Visibility: public -/
def crc8.crc8 (bytes : Slice Std.U8) : Result Std.U8 := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter
      bytes
  crc8.crc8_loop0 iter 0#u8

/-- [framed_channel::channel::encode_frame]:
    Source: 'src/channel.rs', lines 53:0-58:1
    Visibility: public -/
def channel.encode_frame
  (payload : Slice Std.U8) (len : Std.U32) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ← alloc.vec.Vec.push out channel.MARKER
  let out2 ← varint.encode_u32 len out1
  let out3 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 out2 payload
  let i ← crc8.crc8 payload
  alloc.vec.Vec.push out3 i

/-- [framed_channel::varint::decode_u32]: loop body 0:
    Source: 'src/varint.rs', lines 40:4-56:1
    Visibility: public -/
@[rust_loop_body]
def varint.decode_u32_loop.body
  (bytes : Slice Std.U8) (iter : core.ops.range.Range Std.Usize)
  (acc : Std.U32) (shift : Std.U32) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × Std.U32 × Std.U32)
    (core.result.Result (Std.U32 × Std.Usize) varint.VarintError))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (core.result.Result.Err varint.VarintError.Overlong))
  | some i =>
    let o1 ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8) bytes
        i
    match o1 with
    | none => ok (done (core.result.Result.Err varint.VarintError.Truncated))
    | some b =>
      let i1 ← lift (b &&& 127#u8)
      let group ← lift (core.convert.num.FromU32U8.from i1)
      if shift = 28#u32
      then
        if group > 15#u32
        then ok (done (core.result.Result.Err varint.VarintError.Overlong))
        else
          let i2 ← group <<< shift
          let acc1 ← lift (acc ||| i2)
          let i3 ← lift (b &&& 128#u8)
          if i3 = 0#u8
          then
            let i4 ← i + 1#usize
            ok (done (core.result.Result.Ok (acc1, i4)))
          else let shift1 ← shift + 7#u32
               ok (cont (iter1, acc1, shift1))
      else
        let i2 ← group <<< shift
        let acc1 ← lift (acc ||| i2)
        let i3 ← lift (b &&& 128#u8)
        if i3 = 0#u8
        then
          let i4 ← i + 1#usize
          ok (done (core.result.Result.Ok (acc1, i4)))
        else let shift1 ← shift + 7#u32
             ok (cont (iter1, acc1, shift1))

/-- [framed_channel::varint::decode_u32]: loop 0:
    Source: 'src/varint.rs', lines 40:4-56:1
    Visibility: public -/
@[rust_loop]
def varint.decode_u32_loop
  (iter : core.ops.range.Range Std.Usize) (bytes : Slice Std.U8)
  (acc : Std.U32) (shift : Std.U32) :
  Result (core.result.Result (Std.U32 × Std.Usize) varint.VarintError)
  := do
  loop
    (fun (iter1, acc1, shift1) => varint.decode_u32_loop.body bytes iter1 acc1
      shift1)
    (iter, acc, shift)

/-- [framed_channel::varint::decode_u32]:
    Source: 'src/varint.rs', lines 37:0-56:1
    Visibility: public -/
@[reducible]
def varint.decode_u32
  (bytes : Slice Std.U8) :
  Result (core.result.Result (Std.U32 × Std.Usize) varint.VarintError)
  := do
  varint.decode_u32_loop { start := 0#usize, «end» := 5#usize } bytes 0#u32
    0#u32

/-- [framed_channel::channel::parse_frame]:
    Source: 'src/channel.rs', lines 65:0-83:1
    Visibility: public -/
def channel.parse_frame
  (wire : Slice Std.U8) :
  Result (Option ((alloc.vec.Vec Std.U8) × Std.Usize))
  := do
  let o ← core.slice.Slice.split_first wire
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue p =>
    let (first, rest) := p
    if first != channel.MARKER
    then ok none
    else
      let r ← varint.decode_u32 rest
      match r with
      | core.result.Result.Ok p1 =>
        let (n, used) := p1
        let n1 ← lift (UScalar.cast .Usize n)
        let o1 ←
          core.slice.Slice.get (core.slice.index.SliceIndexRangeFromUsizeSlice
            Std.U8) rest { start := used }
        let cf1 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val =>
          let o2 ←
            core.slice.Slice.get (core.slice.index.SliceIndexRangeToUsizeSlice
              Std.U8) val { «end» := n1 }
          let cf2 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o2
          match cf2 with
          | core.ops.control_flow.ControlFlow.Continue val1 =>
            let payload ← alloc.slice.Slice.to_vec core.clone.CloneU8 val1
            let o3 ←
              core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice
                Std.U8) val n1
            let cf3 ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o3
            match cf3 with
            | core.ops.control_flow.ControlFlow.Continue val2 =>
              let s := alloc.vec.Vec.deref payload
              let i ← crc8.crc8 s
              if val2 != i
              then ok none
              else
                let i1 ← 1#usize + used
                let i2 ← i1 + n1
                let i3 ← i2 + 1#usize
                ok (some (payload, i3))
            | core.ops.control_flow.ControlFlow.Break residual =>
              core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
                ((alloc.vec.Vec Std.U8) × Std.Usize) residual
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
              ((alloc.vec.Vec Std.U8) × Std.Usize) residual
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
            ((alloc.vec.Vec Std.U8) × Std.Usize) residual
      | core.result.Result.Err _ => ok none
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionNever.from_residual
      ((alloc.vec.Vec Std.U8) × Std.Usize) residual

/-- [framed_channel::channel::drop_front]:
    Source: 'src/channel.rs', lines 87:0-92:1 -/
def channel.drop_front
  (bytes : Slice Std.U8) (n : Std.Usize) : Result (alloc.vec.Vec Std.U8) := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexRangeFromUsizeSlice
      Std.U8) bytes { start := n }
  match o with
  | none => ok (alloc.vec.Vec.new Std.U8)
  | some rest => alloc.slice.Slice.to_vec core.clone.CloneU8 rest

/-- [framed_channel::channel::{impl core::fmt::Debug for framed_channel::channel::Channel<Q>}::fmt]:
    Source: 'src/channel.rs', lines 96:9-96:14
    Visibility: public -/
def channel.Channel.Insts.CoreFmtDebug.fmt
  {Q : Type} (corefmtDebugInst : core.fmt.Debug Q) (self : channel.Channel Q)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ corefmtDebugInst self.out
  let dyn1 := Dyn.mk _ (core.fmt.DebugVec core.fmt.DebugU8) self.wire
  let dyn2 :=
    Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) self.in_flight
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Channel") (toStr
    "out") dyn (toStr "wire") dyn1 (toStr "in_flight") dyn2

/-- Trait implementation: [framed_channel::channel::{impl core::fmt::Debug for framed_channel::channel::Channel<Q>}]
    Source: 'src/channel.rs', lines 96:9-96:14 -/
@[reducible]
def channel.Channel.Insts.CoreFmtDebug {Q : Type} (corefmtDebugInst :
  core.fmt.Debug Q) : core.fmt.Debug (channel.Channel Q) := {
  fmt := channel.Channel.Insts.CoreFmtDebug.fmt corefmtDebugInst
}

/-- [framed_channel::channel::{impl core::clone::Clone for framed_channel::channel::Channel<Q>}::clone]:
    Source: 'src/channel.rs', lines 96:16-96:21
    Visibility: public -/
def channel.Channel.Insts.CoreCloneClone.clone
  {Q : Type} (corecloneCloneInst : core.clone.Clone Q)
  (self : channel.Channel Q) :
  Result (channel.Channel Q)
  := do
  let t ← corecloneCloneInst.clone self.out
  let v ← alloc.vec.CloneVec.clone core.clone.CloneU8 self.wire
  let i ← lift (core.clone.impls.CloneUsize.clone self.in_flight)
  ok { out := t, wire := v, in_flight := i }

/-- Trait implementation: [framed_channel::channel::{impl core::clone::Clone for framed_channel::channel::Channel<Q>}]
    Source: 'src/channel.rs', lines 96:16-96:21 -/
@[reducible]
def channel.Channel.Insts.CoreCloneClone {Q : Type} (corecloneCloneInst :
  core.clone.Clone Q) : core.clone.Clone (channel.Channel Q) := {
  clone := channel.Channel.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::get]:
    Source: 'src/ring_buffer.rs', lines 63:4-68:5 -/
def ring_buffer.RingBuffer.get
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T)
  (i : Std.Usize) :
  Result T
  := do
  let s := alloc.vec.Vec.deref self.buf
  let o ← core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice T) s i
  match o with
  | none => coredefaultDefaultInst.default
  | some v => corecloneCloneInst.clone v

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::contents]: loop body 0:
    Source: 'src/ring_buffer.rs', lines 113:8-115:9
    Visibility: public -/
@[rust_loop_body]
def ring_buffer.RingBuffer.contents_loop.body
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (v : alloc.vec.Vec T)
  (i : Std.Usize) (i1 : Std.Usize) (i2 : Std.Usize) (cap : Std.Usize)
  (iter : core.ops.range.Range Std.Usize) (out : alloc.vec.Vec T) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (alloc.vec.Vec T))
    (alloc.vec.Vec T))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done out)
  | some i3 =>
    let i4 ← i + i3
    let i5 ← i4 % cap
    let t ←
      ring_buffer.RingBuffer.get coredefaultDefaultInst corecloneCloneInst
        { buf := v, head := i, tail := i1, len := i2 } i5
    let out1 ← alloc.vec.Vec.push out t
    ok (cont (iter1, out1))

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::contents]: loop 0:
    Source: 'src/ring_buffer.rs', lines 113:8-115:9
    Visibility: public -/
@[rust_loop]
def ring_buffer.RingBuffer.contents_loop
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T)
  (iter : core.ops.range.Range Std.Usize) (v : alloc.vec.Vec T) (i : Std.Usize)
  (i1 : Std.Usize) (i2 : Std.Usize) (out : alloc.vec.Vec T) (cap : Std.Usize) :
  Result (alloc.vec.Vec T)
  := do
  loop
    (fun (iter1, out1) => ring_buffer.RingBuffer.contents_loop.body
      coredefaultDefaultInst corecloneCloneInst v i i1 i2 cap iter1 out1)
    (iter, out)

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::contents]:
    Source: 'src/ring_buffer.rs', lines 110:4-117:5
    Visibility: public -/
def ring_buffer.RingBuffer.contents
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result (alloc.vec.Vec T)
  := do
  let cap := alloc.vec.Vec.len self.buf
  ring_buffer.RingBuffer.contents_loop coredefaultDefaultInst
    corecloneCloneInst { start := 0#usize, «end» := self.len } self.buf
    self.head self.tail self.len (alloc.vec.Vec.new T) cap

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::contents]:
    Source: 'src/ring_buffer.rs', lines 149:4-151:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.contents
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result (alloc.vec.Vec T)
  := do
  ring_buffer.RingBuffer.contents coredefaultDefaultInst corecloneCloneInst
    self

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::pop]:
    Source: 'src/ring_buffer.rs', lines 96:4-105:5
    Visibility: public -/
def ring_buffer.RingBuffer.pop
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result ((Option T) × (ring_buffer.RingBuffer T))
  := do
  if self.len = 0#usize
  then ok (none, self)
  else
    let cap := alloc.vec.Vec.len self.buf
    let x ←
      ring_buffer.RingBuffer.get coredefaultDefaultInst corecloneCloneInst self
        self.head
    let i ← self.head + 1#usize
    let i1 ← i % cap
    let i2 ← self.len - 1#usize
    ok (some x, { self with head := i1, len := i2 })

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::pop]:
    Source: 'src/ring_buffer.rs', lines 145:4-147:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.pop
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result ((Option T) × (ring_buffer.RingBuffer T))
  := do
  ring_buffer.RingBuffer.pop coredefaultDefaultInst corecloneCloneInst self

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::set]:
    Source: 'src/ring_buffer.rs', lines 71:4-75:5 -/
def ring_buffer.RingBuffer.set
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T)
  (i : Std.Usize) (x : T) :
  Result (ring_buffer.RingBuffer T)
  := do
  let (s, deref_mut_back) ← lift (alloc.vec.Vec.deref_mut self.buf)
  let (o, get_mut_back) ←
    core.slice.Slice.get_mut (core.slice.index.SliceIndexUsizeSlice T) s i
  match o with
  | none =>
    let s1 := get_mut_back none
    let v := deref_mut_back s1
    ok { self with buf := v }
  | some _ =>
    let s1 := get_mut_back (some x)
    let v := deref_mut_back s1
    ok { self with buf := v }

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::push]:
    Source: 'src/ring_buffer.rs', lines 83:4-92:5
    Visibility: public -/
def ring_buffer.RingBuffer.push
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T)
  (x : T) :
  Result ((core.result.Result Unit ring_buffer.Full) × (ring_buffer.RingBuffer
    T))
  := do
  let i := alloc.vec.Vec.len self.buf
  if self.len = i
  then ok (core.result.Result.Err (), self)
  else
    let cap := alloc.vec.Vec.len self.buf
    let self1 ←
      ring_buffer.RingBuffer.set coredefaultDefaultInst corecloneCloneInst self
        self.tail x
    let i1 ← self1.tail + 1#usize
    let i2 ← i1 % cap
    let i3 ← self1.len + 1#usize
    ok (core.result.Result.Ok (), { self1 with tail := i2, len := i3 })

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::push]:
    Source: 'src/ring_buffer.rs', lines 141:4-143:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.push
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T)
  (x : T) :
  Result ((core.result.Result Unit ring_buffer.Full) × (ring_buffer.RingBuffer
    T))
  := do
  ring_buffer.RingBuffer.push coredefaultDefaultInst corecloneCloneInst self x

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::is_full]:
    Source: 'src/ring_buffer.rs', lines 58:4-60:5
    Visibility: public -/
def ring_buffer.RingBuffer.is_full
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Bool
  := do
  let i := alloc.vec.Vec.len self.buf
  ok (self.len = i)

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::is_full]:
    Source: 'src/ring_buffer.rs', lines 137:4-139:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.is_full
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Bool
  := do
  ring_buffer.RingBuffer.is_full coredefaultDefaultInst corecloneCloneInst self

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::is_empty]:
    Source: 'src/ring_buffer.rs', lines 52:4-54:5
    Visibility: public -/
def ring_buffer.RingBuffer.is_empty
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Bool
  := do
  ok (self.len = 0#usize)

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::is_empty]:
    Source: 'src/ring_buffer.rs', lines 133:4-135:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.is_empty
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Bool
  := do
  ring_buffer.RingBuffer.is_empty coredefaultDefaultInst corecloneCloneInst
    self

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::len]:
    Source: 'src/ring_buffer.rs', lines 46:4-48:5
    Visibility: public -/
def ring_buffer.RingBuffer.impl.len
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Std.Usize
  := do
  ok self.len

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::len]:
    Source: 'src/ring_buffer.rs', lines 129:4-131:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.len
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Std.Usize
  := do
  ring_buffer.RingBuffer.impl.len coredefaultDefaultInst corecloneCloneInst
    self

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::capacity]:
    Source: 'src/ring_buffer.rs', lines 40:4-42:5
    Visibility: public -/
def ring_buffer.RingBuffer.capacity
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Std.Usize
  := do
  ok (alloc.vec.Vec.len self.buf)

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::capacity]:
    Source: 'src/ring_buffer.rs', lines 125:4-127:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.capacity
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (self : ring_buffer.RingBuffer T) :
  Result Std.Usize
  := do
  ring_buffer.RingBuffer.capacity coredefaultDefaultInst corecloneCloneInst
    self

/-- [framed_channel::ring_buffer::{framed_channel::ring_buffer::RingBuffer<T>}::with_capacity]:
    Source: 'src/ring_buffer.rs', lines 33:4-36:5
    Visibility: public -/
def ring_buffer.RingBuffer.with_capacity
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (cap : Std.Usize) :
  Result (ring_buffer.RingBuffer T)
  := do
  let cap1 ← if cap = 0#usize
               then ok 1#usize
               else ok cap
  let t ← coredefaultDefaultInst.default
  let v ← alloc.vec.from_elem corecloneCloneInst t cap1
  ok { buf := v, head := 0#usize, tail := 0#usize, len := 0#usize }

/-- [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}::with_capacity]:
    Source: 'src/ring_buffer.rs', lines 121:4-123:5
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.with_capacity
  {T : Type} (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) (cap : Std.Usize) :
  Result (ring_buffer.RingBuffer T)
  := do
  ring_buffer.RingBuffer.with_capacity coredefaultDefaultInst
    corecloneCloneInst cap

/-- Trait implementation: [framed_channel::ring_buffer::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::ring_buffer::RingBuffer<T>}]
    Source: 'src/ring_buffer.rs', lines 120:0-152:1 -/
@[reducible]
def ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue {T : Type}
  (coredefaultDefaultInst : core.default.Default T) (corecloneCloneInst :
  core.clone.Clone T) : queue.BoundedQueue (ring_buffer.RingBuffer T) T := {
  with_capacity :=
    ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.with_capacity
    coredefaultDefaultInst corecloneCloneInst
  capacity :=
    ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.capacity
    coredefaultDefaultInst corecloneCloneInst
  len := ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.len
    coredefaultDefaultInst corecloneCloneInst
  is_empty :=
    ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.is_empty
    coredefaultDefaultInst corecloneCloneInst
  is_full :=
    ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.is_full
    coredefaultDefaultInst corecloneCloneInst
  push := ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.push
    coredefaultDefaultInst corecloneCloneInst
  pop := ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.pop
    coredefaultDefaultInst corecloneCloneInst
  contents :=
    ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue.contents
    coredefaultDefaultInst corecloneCloneInst
}

/-- [framed_channel::channel::{framed_channel::channel::Channel<Q>}::with_queue]:
    Source: 'src/channel.rs', lines 116:4-118:5
    Visibility: public -/
def channel.Channel.with_queue
  {Q : Type} (queueBoundedQueueQVecU8Inst : queue.BoundedQueue Q (alloc.vec.Vec
  Std.U8)) (capacity : Std.Usize) :
  Result (channel.Channel Q)
  := do
  let t ← queueBoundedQueueQVecU8Inst.with_capacity capacity
  ok { out := t, wire := (alloc.vec.Vec.new Std.U8), in_flight := 0#usize }

/-- [framed_channel::channel::{framed_channel::channel::Channel<framed_channel::ring_buffer::RingBuffer<alloc::vec::Vec<u8>>>}::new]:
    Source: 'src/channel.rs', lines 108:4-110:5
    Visibility: public -/
def channel.ChannelRingBufferVecU8.new
  (capacity : Std.Usize) :
  Result (channel.Channel (ring_buffer.RingBuffer (alloc.vec.Vec Std.U8)))
  := do
  channel.Channel.with_queue
    (ring_buffer.RingBuffer.Insts.Framed_channelQueueBoundedQueue
    (alloc.vec.Vec.Insts.CoreDefaultDefault Std.U8)
    (core.clone.CloneallocvecVec core.clone.CloneU8)) capacity

/-- [framed_channel::channel::{framed_channel::channel::Channel<Q>}::send]:
    Source: 'src/channel.rs', lines 130:4-140:5
    Visibility: public -/
def channel.Channel.send
  {Q : Type} (queueBoundedQueueQVecU8Inst : queue.BoundedQueue Q (alloc.vec.Vec
  Std.U8)) (self : channel.Channel Q) (payload : Slice Std.U8) :
  Result ((core.result.Result Unit channel.SendFail) × (channel.Channel Q))
  := do
  let i ← queueBoundedQueueQVecU8Inst.len self.out
  let i1 ← i + self.in_flight
  let i2 ← queueBoundedQueueQVecU8Inst.capacity self.out
  if i1 >= i2
  then ok (core.result.Result.Err (), self)
  else
    let i3 := Slice.len payload
    let r ← core.convert.num.ptr_try_from_impls.TryFromU32Usize.try_from i3
    match r with
    | core.result.Result.Ok len =>
      let v ← channel.encode_frame payload len self.wire
      let i4 ← self.in_flight + 1#usize
      ok (core.result.Result.Ok (), { self with wire := v, in_flight := i4 })
    | core.result.Result.Err _ => ok (core.result.Result.Err (), self)

/-- [framed_channel::channel::{framed_channel::channel::Channel<Q>}::deliver]:
    Source: 'src/channel.rs', lines 150:4-165:5
    Visibility: public -/
def channel.Channel.deliver
  {Q : Type} (queueBoundedQueueQVecU8Inst : queue.BoundedQueue Q (alloc.vec.Vec
  Std.U8)) (self : channel.Channel Q) :
  Result ((core.result.Result (alloc.vec.Vec Std.U8) channel.DeliverFail) ×
    (channel.Channel Q))
  := do
  let s := alloc.vec.Vec.deref self.wire
  let o ← channel.parse_frame s
  match o with
  | none => ok (core.result.Result.Err (), self)
  | some p =>
    let (payload, used) := p
    let v ← alloc.vec.CloneVec.clone core.clone.CloneU8 payload
    let (r, t) ← queueBoundedQueueQVecU8Inst.push self.out v
    match r with
    | core.result.Result.Ok _ =>
      let s1 := alloc.vec.Vec.deref self.wire
      let v1 ← channel.drop_front s1 used
      let i ← lift (core.num.Usize.saturating_sub self.in_flight 1#usize)
      ok (core.result.Result.Ok payload,
        { out := t, wire := v1, in_flight := i })
    | core.result.Result.Err _ =>
      ok (core.result.Result.Err (), { self with out := t })

/-- [framed_channel::channel::{framed_channel::channel::Channel<Q>}::take]:
    Source: 'src/channel.rs', lines 168:4-170:5
    Visibility: public -/
def channel.Channel.take
  {Q : Type} (queueBoundedQueueQVecU8Inst : queue.BoundedQueue Q (alloc.vec.Vec
  Std.U8)) (self : channel.Channel Q) :
  Result ((Option (alloc.vec.Vec Std.U8)) × (channel.Channel Q))
  := do
  let (o, t) ← queueBoundedQueueQVecU8Inst.pop self.out
  ok (o, { self with out := t })

/-- [framed_channel::channel::{framed_channel::channel::Channel<Q>}::queued]:
    Source: 'src/channel.rs', lines 173:4-175:5
    Visibility: public -/
def channel.Channel.queued
  {Q : Type} (queueBoundedQueueQVecU8Inst : queue.BoundedQueue Q (alloc.vec.Vec
  Std.U8)) (self : channel.Channel Q) :
  Result Std.Usize
  := do
  queueBoundedQueueQVecU8Inst.len self.out

/-- [framed_channel::crc8::TABLE]
    Source: 'src/crc8.rs', lines 25:0-42:2
    Visibility: public -/
@[global_simps, irreducible]
def crc8.TABLE : Array Std.U8 256#usize :=
  Array.make 256#usize [
    0#u8, 7#u8, 14#u8, 9#u8, 28#u8, 27#u8, 18#u8, 21#u8, 56#u8, 63#u8, 54#u8,
    49#u8, 36#u8, 35#u8, 42#u8, 45#u8, 112#u8, 119#u8, 126#u8, 121#u8, 108#u8,
    107#u8, 98#u8, 101#u8, 72#u8, 79#u8, 70#u8, 65#u8, 84#u8, 83#u8, 90#u8,
    93#u8, 224#u8, 231#u8, 238#u8, 233#u8, 252#u8, 251#u8, 242#u8, 245#u8,
    216#u8, 223#u8, 214#u8, 209#u8, 196#u8, 195#u8, 202#u8, 205#u8, 144#u8,
    151#u8, 158#u8, 153#u8, 140#u8, 139#u8, 130#u8, 133#u8, 168#u8, 175#u8,
    166#u8, 161#u8, 180#u8, 179#u8, 186#u8, 189#u8, 199#u8, 192#u8, 201#u8,
    206#u8, 219#u8, 220#u8, 213#u8, 210#u8, 255#u8, 248#u8, 241#u8, 246#u8,
    227#u8, 228#u8, 237#u8, 234#u8, 183#u8, 176#u8, 185#u8, 190#u8, 171#u8,
    172#u8, 165#u8, 162#u8, 143#u8, 136#u8, 129#u8, 134#u8, 147#u8, 148#u8,
    157#u8, 154#u8, 39#u8, 32#u8, 41#u8, 46#u8, 59#u8, 60#u8, 53#u8, 50#u8,
    31#u8, 24#u8, 17#u8, 22#u8, 3#u8, 4#u8, 13#u8, 10#u8, 87#u8, 80#u8, 89#u8,
    94#u8, 75#u8, 76#u8, 69#u8, 66#u8, 111#u8, 104#u8, 97#u8, 102#u8, 115#u8,
    116#u8, 125#u8, 122#u8, 137#u8, 142#u8, 135#u8, 128#u8, 149#u8, 146#u8,
    155#u8, 156#u8, 177#u8, 182#u8, 191#u8, 184#u8, 173#u8, 170#u8, 163#u8,
    164#u8, 249#u8, 254#u8, 247#u8, 240#u8, 229#u8, 226#u8, 235#u8, 236#u8,
    193#u8, 198#u8, 207#u8, 200#u8, 221#u8, 218#u8, 211#u8, 212#u8, 105#u8,
    110#u8, 103#u8, 96#u8, 117#u8, 114#u8, 123#u8, 124#u8, 81#u8, 86#u8, 95#u8,
    88#u8, 77#u8, 74#u8, 67#u8, 68#u8, 25#u8, 30#u8, 23#u8, 16#u8, 5#u8, 2#u8,
    11#u8, 12#u8, 33#u8, 38#u8, 47#u8, 40#u8, 61#u8, 58#u8, 51#u8, 52#u8,
    78#u8, 73#u8, 64#u8, 71#u8, 82#u8, 85#u8, 92#u8, 91#u8, 118#u8, 113#u8,
    120#u8, 127#u8, 106#u8, 109#u8, 100#u8, 99#u8, 62#u8, 57#u8, 48#u8, 55#u8,
    34#u8, 37#u8, 44#u8, 43#u8, 6#u8, 1#u8, 8#u8, 15#u8, 26#u8, 29#u8, 20#u8,
    19#u8, 174#u8, 169#u8, 160#u8, 167#u8, 178#u8, 181#u8, 188#u8, 187#u8,
    150#u8, 145#u8, 152#u8, 159#u8, 138#u8, 141#u8, 132#u8, 131#u8, 222#u8,
    217#u8, 208#u8, 215#u8, 194#u8, 197#u8, 204#u8, 203#u8, 230#u8, 225#u8,
    232#u8, 239#u8, 250#u8, 253#u8, 244#u8, 243#u8
    ]

/-- [framed_channel::crc8::crc8_table]: loop body 0:
    Source: 'src/crc8.rs', lines 49:14-49:19
    Visibility: public -/
@[rust_loop_body]
def crc8.crc8_table_loop.body
  (iter : core.slice.iter.Iter Std.U8) (crc : Std.U8) :
  Result (ControlFlow ((core.slice.iter.Iter Std.U8) × Std.U8) Std.U8)
  := do
  let (o, iter1) ← core.slice.iter.IteratorSliceIter.next iter
  match o with
  | none => ok (done crc)
  | some b =>
    let s ← lift (Array.to_slice crc8.TABLE)
    let i ← lift (crc ^^^ b)
    let i1 ← lift (UScalar.cast .Usize i)
    let o1 ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8) s i1
    match o1 with
    | none => ok (cont (iter1, 0#u8))
    | some v => ok (cont (iter1, v))

/-- [framed_channel::crc8::crc8_table]: loop 0:
    Source: 'src/crc8.rs', lines 49:14-49:19
    Visibility: public -/
@[rust_loop]
def crc8.crc8_table_loop
  (iter : core.slice.iter.Iter Std.U8) (crc : Std.U8) : Result Std.U8 := do
  loop
    (fun (iter1, crc1) => crc8.crc8_table_loop.body iter1 crc1)
    (iter, crc)

/-- [framed_channel::crc8::crc8_table]:
    Source: 'src/crc8.rs', lines 47:0-56:1
    Visibility: public -/
def crc8.crc8_table (bytes : Slice Std.U8) : Result Std.U8 := do
  let iter ←
    SharedSlice.Insts.CoreIterTraitsCollectIntoIteratorSharedIter.into_iter
      bytes
  crc8.crc8_table_loop iter 0#u8

/-- [framed_channel::queue::{impl core::fmt::Debug for framed_channel::queue::VecQueue<T>}::fmt]:
    Source: 'src/queue.rs', lines 53:9-53:14
    Visibility: public -/
def queue.VecQueue.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (self : queue.VecQueue T)
  (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugVec corefmtDebugInst) self.items
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) self.cap
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "VecQueue") (toStr
    "items") dyn (toStr "cap") dyn1

/-- Trait implementation: [framed_channel::queue::{impl core::fmt::Debug for framed_channel::queue::VecQueue<T>}]
    Source: 'src/queue.rs', lines 53:9-53:14 -/
@[reducible]
def queue.VecQueue.Insts.CoreFmtDebug {T : Type} (corefmtDebugInst :
  core.fmt.Debug T) : core.fmt.Debug (queue.VecQueue T) := {
  fmt := queue.VecQueue.Insts.CoreFmtDebug.fmt corefmtDebugInst
}

/-- [framed_channel::queue::{impl core::clone::Clone for framed_channel::queue::VecQueue<T>}::clone]:
    Source: 'src/queue.rs', lines 53:16-53:21
    Visibility: public -/
def queue.VecQueue.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result (queue.VecQueue T)
  := do
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self.items
  let i ← lift (core.clone.impls.CloneUsize.clone self.cap)
  ok { items := v, cap := i }

/-- Trait implementation: [framed_channel::queue::{impl core::clone::Clone for framed_channel::queue::VecQueue<T>}]
    Source: 'src/queue.rs', lines 53:16-53:21 -/
@[reducible]
def queue.VecQueue.Insts.CoreCloneClone {T : Type} (corecloneCloneInst :
  core.clone.Clone T) : core.clone.Clone (queue.VecQueue T) := {
  clone := queue.VecQueue.Insts.CoreCloneClone.clone corecloneCloneInst
}

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::with_capacity]:
    Source: 'src/queue.rs', lines 64:4-66:5
    Visibility: public -/
def queue.VecQueue.with_capacity
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (cap : Std.Usize) :
  Result (queue.VecQueue T)
  := do
  ok { items := (alloc.vec.Vec.new T), cap }

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::capacity]:
    Source: 'src/queue.rs', lines 70:4-72:5
    Visibility: public -/
def queue.VecQueue.capacity
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Std.Usize
  := do
  ok self.cap

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::len]:
    Source: 'src/queue.rs', lines 76:4-78:5
    Visibility: public -/
def queue.VecQueue.len
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Std.Usize
  := do
  ok (alloc.vec.Vec.len self.items)

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::is_empty]:
    Source: 'src/queue.rs', lines 83:4-85:5
    Visibility: public -/
def queue.VecQueue.is_empty
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Bool
  := do
  let i ← queue.VecQueue.len corecloneCloneInst self
  ok (i = 0#usize)

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::is_full]:
    Source: 'src/queue.rs', lines 89:4-91:5
    Visibility: public -/
def queue.VecQueue.is_full
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Bool
  := do
  let i := alloc.vec.Vec.len self.items
  ok (self.cap <= i)

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::push]:
    Source: 'src/queue.rs', lines 98:4-104:5
    Visibility: public -/
def queue.VecQueue.push
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) (x : T) :
  Result ((core.result.Result Unit ring_buffer.Full) × (queue.VecQueue T))
  := do
  let i := alloc.vec.Vec.len self.items
  if self.cap <= i
  then ok (core.result.Result.Err (), self)
  else
    let v ← alloc.vec.Vec.push self.items x
    ok (core.result.Result.Ok (), { self with items := v })

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::pop]:
    Source: 'src/queue.rs', lines 108:4-114:5
    Visibility: public -/
def queue.VecQueue.pop
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result ((Option T) × (queue.VecQueue T))
  := do
  let b ← queue.VecQueue.is_empty corecloneCloneInst self
  if b
  then ok (none, self)
  else
    let (t, v) ← alloc.vec.Vec.remove Global self.items 0#usize
    ok (some t, { self with items := v })

/-- [framed_channel::queue::{framed_channel::queue::VecQueue<T>}::contents]:
    Source: 'src/queue.rs', lines 119:4-121:5
    Visibility: public -/
def queue.VecQueue.contents
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result (alloc.vec.Vec T)
  := do
  alloc.vec.CloneVec.clone corecloneCloneInst self.items

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::contents]:
    Source: 'src/queue.rs', lines 153:4-155:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.contents
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result (alloc.vec.Vec T)
  := do
  queue.VecQueue.contents corecloneCloneInst self

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::pop]:
    Source: 'src/queue.rs', lines 149:4-151:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.pop
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result ((Option T) × (queue.VecQueue T))
  := do
  queue.VecQueue.pop corecloneCloneInst self

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::push]:
    Source: 'src/queue.rs', lines 145:4-147:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.push
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) (x : T) :
  Result ((core.result.Result Unit ring_buffer.Full) × (queue.VecQueue T))
  := do
  queue.VecQueue.push corecloneCloneInst self x

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::is_full]:
    Source: 'src/queue.rs', lines 141:4-143:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.is_full
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Bool
  := do
  queue.VecQueue.is_full corecloneCloneInst self

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::is_empty]:
    Source: 'src/queue.rs', lines 137:4-139:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.is_empty
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Bool
  := do
  queue.VecQueue.is_empty corecloneCloneInst self

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::len]:
    Source: 'src/queue.rs', lines 133:4-135:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.len
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Std.Usize
  := do
  queue.VecQueue.len corecloneCloneInst self

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::capacity]:
    Source: 'src/queue.rs', lines 129:4-131:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.capacity
  {T : Type} (corecloneCloneInst : core.clone.Clone T)
  (self : queue.VecQueue T) :
  Result Std.Usize
  := do
  queue.VecQueue.capacity corecloneCloneInst self

/-- [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}::with_capacity]:
    Source: 'src/queue.rs', lines 125:4-127:5
    Visibility: public -/
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.with_capacity
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (cap : Std.Usize) :
  Result (queue.VecQueue T)
  := do
  queue.VecQueue.with_capacity corecloneCloneInst cap

/-- Trait implementation: [framed_channel::queue::{impl framed_channel::queue::BoundedQueue<T> for framed_channel::queue::VecQueue<T>}]
    Source: 'src/queue.rs', lines 124:0-156:1 -/
@[reducible]
def queue.VecQueue.Insts.Framed_channelQueueBoundedQueue {T : Type}
  (corecloneCloneInst : core.clone.Clone T) : queue.BoundedQueue
  (queue.VecQueue T) T := {
  with_capacity :=
    queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.with_capacity
    corecloneCloneInst
  capacity := queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.capacity
    corecloneCloneInst
  len := queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.len
    corecloneCloneInst
  is_empty := queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.is_empty
    corecloneCloneInst
  is_full := queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.is_full
    corecloneCloneInst
  push := queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.push
    corecloneCloneInst
  pop := queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.pop
    corecloneCloneInst
  contents := queue.VecQueue.Insts.Framed_channelQueueBoundedQueue.contents
    corecloneCloneInst
}

/-- [framed_channel::ring_buffer::{impl core::fmt::Debug for framed_channel::ring_buffer::Full}::fmt]:
    Source: 'src/ring_buffer.rs', lines 17:9-17:14
    Visibility: public -/
def ring_buffer.Full.Insts.CoreFmtDebug.fmt
  (self : ring_buffer.Full) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  core.fmt.Formatter.write_str f (toStr "Full")

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::fmt::Debug for framed_channel::ring_buffer::Full}]
    Source: 'src/ring_buffer.rs', lines 17:9-17:14 -/
@[reducible]
def ring_buffer.Full.Insts.CoreFmtDebug : core.fmt.Debug ring_buffer.Full := {
  fmt := ring_buffer.Full.Insts.CoreFmtDebug.fmt
}

/-- [framed_channel::ring_buffer::{impl core::clone::Clone for framed_channel::ring_buffer::Full}::clone]:
    Source: 'src/ring_buffer.rs', lines 17:16-17:21
    Visibility: public -/
def ring_buffer.Full.Insts.CoreCloneClone.clone
  (self : ring_buffer.Full) : Result ring_buffer.Full := do
  ok self

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::clone::Clone for framed_channel::ring_buffer::Full}]
    Source: 'src/ring_buffer.rs', lines 17:16-17:21 -/
@[reducible]
def ring_buffer.Full.Insts.CoreCloneClone : core.clone.Clone ring_buffer.Full
  := {
  clone := ring_buffer.Full.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::marker::Copy for framed_channel::ring_buffer::Full}]
    Source: 'src/ring_buffer.rs', lines 17:23-17:27 -/
@[reducible]
def ring_buffer.Full.Insts.CoreMarkerCopy : core.marker.Copy ring_buffer.Full
  := {
  cloneInst := ring_buffer.Full.Insts.CoreCloneClone
}

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::marker::StructuralPartialEq for framed_channel::ring_buffer::Full}]
    Source: 'src/ring_buffer.rs', lines 17:29-17:38 -/
@[reducible]
def ring_buffer.Full.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq ring_buffer.Full := {
}

/-- [framed_channel::ring_buffer::{impl core::cmp::PartialEq<framed_channel::ring_buffer::Full> for framed_channel::ring_buffer::Full}::eq]:
    Source: 'src/ring_buffer.rs', lines 17:29-17:38
    Visibility: public -/
def ring_buffer.Full.Insts.CoreCmpPartialEqFull.eq
  (self : ring_buffer.Full) (other : ring_buffer.Full) : Result Bool := do
  ok true

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::cmp::PartialEq<framed_channel::ring_buffer::Full> for framed_channel::ring_buffer::Full}]
    Source: 'src/ring_buffer.rs', lines 17:29-17:38 -/
@[reducible]
def ring_buffer.Full.Insts.CoreCmpPartialEqFull : core.cmp.PartialEq
  ring_buffer.Full ring_buffer.Full := {
  eq := ring_buffer.Full.Insts.CoreCmpPartialEqFull.eq
}

/-- [framed_channel::ring_buffer::{impl core::cmp::Eq for framed_channel::ring_buffer::Full}::assert_fields_are_eq]:
    Source: 'src/ring_buffer.rs', lines 17:40-17:42
    Visibility: public -/
def ring_buffer.Full.Insts.CoreCmpEq.assert_fields_are_eq
  (self : ring_buffer.Full) : Result Unit := do
  ok ()

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::cmp::Eq for framed_channel::ring_buffer::Full}]
    Source: 'src/ring_buffer.rs', lines 17:40-17:42 -/
@[reducible]
def ring_buffer.Full.Insts.CoreCmpEq : core.cmp.Eq ring_buffer.Full := {
  partialEqInst := ring_buffer.Full.Insts.CoreCmpPartialEqFull
  assert_fields_are_eq := ring_buffer.Full.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [framed_channel::ring_buffer::{impl core::fmt::Debug for framed_channel::ring_buffer::RingBuffer<T>}::fmt]:
    Source: 'src/ring_buffer.rs', lines 22:9-22:14
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) (coredefaultDefaultInst :
  core.default.Default T) (corecloneCloneInst : core.clone.Clone T)
  (self : ring_buffer.RingBuffer T) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugVec corefmtDebugInst) self.buf
  let dyn1 := Dyn.mk _ core.fmt.DebugUsize self.head
  let dyn2 := Dyn.mk _ core.fmt.DebugUsize self.tail
  let dyn3 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugUsize) self.len
  core.fmt.Formatter.debug_struct_field4_finish f (toStr "RingBuffer") (toStr
    "buf") dyn (toStr "head") dyn1 (toStr "tail") dyn2 (toStr "len") dyn3

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::fmt::Debug for framed_channel::ring_buffer::RingBuffer<T>}]
    Source: 'src/ring_buffer.rs', lines 22:9-22:14 -/
@[reducible]
def ring_buffer.RingBuffer.Insts.CoreFmtDebug {T : Type} (corefmtDebugInst :
  core.fmt.Debug T) (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst : core.clone.Clone T) : core.fmt.Debug
  (ring_buffer.RingBuffer T) := {
  fmt := ring_buffer.RingBuffer.Insts.CoreFmtDebug.fmt corefmtDebugInst
    coredefaultDefaultInst corecloneCloneInst
}

/-- [framed_channel::ring_buffer::{impl core::clone::Clone for framed_channel::ring_buffer::RingBuffer<T>}::clone]:
    Source: 'src/ring_buffer.rs', lines 22:16-22:21
    Visibility: public -/
def ring_buffer.RingBuffer.Insts.CoreCloneClone.clone
  {T : Type} (corecloneCloneInst : core.clone.Clone T) (coredefaultDefaultInst
  : core.default.Default T) (corecloneCloneInst1 : core.clone.Clone T)
  (self : ring_buffer.RingBuffer T) :
  Result (ring_buffer.RingBuffer T)
  := do
  let v ← alloc.vec.CloneVec.clone corecloneCloneInst self.buf
  let i ← lift (core.clone.impls.CloneUsize.clone self.head)
  let i1 ← lift (core.clone.impls.CloneUsize.clone self.tail)
  let i2 ← lift (core.clone.impls.CloneUsize.clone self.len)
  ok { buf := v, head := i, tail := i1, len := i2 }

/-- Trait implementation: [framed_channel::ring_buffer::{impl core::clone::Clone for framed_channel::ring_buffer::RingBuffer<T>}]
    Source: 'src/ring_buffer.rs', lines 22:16-22:21 -/
@[reducible]
def ring_buffer.RingBuffer.Insts.CoreCloneClone {T : Type} (corecloneCloneInst
  : core.clone.Clone T) (coredefaultDefaultInst : core.default.Default T)
  (corecloneCloneInst1 : core.clone.Clone T) : core.clone.Clone
  (ring_buffer.RingBuffer T) := {
  clone := ring_buffer.RingBuffer.Insts.CoreCloneClone.clone corecloneCloneInst
    coredefaultDefaultInst corecloneCloneInst
}

/-- [framed_channel::seq_num::HALF]
    Source: 'src/seq_num.rs', lines 31:0-31:25 -/
@[global_simps, irreducible] def seq_num.HALF : Std.U16 := 32768#u16

/-- [framed_channel::seq_num::{impl core::fmt::Debug for framed_channel::seq_num::SeqNum}::fmt]:
    Source: 'src/seq_num.rs', lines 34:9-34:14
    Visibility: public -/
def seq_num.SeqNum.Insts.CoreFmtDebug.fmt
  (self : seq_num.SeqNum) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU16) self.value
  core.fmt.Formatter.debug_struct_field1_finish f (toStr "SeqNum") (toStr
    "value") dyn

/-- Trait implementation: [framed_channel::seq_num::{impl core::fmt::Debug for framed_channel::seq_num::SeqNum}]
    Source: 'src/seq_num.rs', lines 34:9-34:14 -/
@[reducible]
def seq_num.SeqNum.Insts.CoreFmtDebug : core.fmt.Debug seq_num.SeqNum := {
  fmt := seq_num.SeqNum.Insts.CoreFmtDebug.fmt
}

/-- [framed_channel::seq_num::{impl core::clone::Clone for framed_channel::seq_num::SeqNum}::clone]:
    Source: 'src/seq_num.rs', lines 34:16-34:21
    Visibility: public -/
def seq_num.SeqNum.Insts.CoreCloneClone.clone
  (self : seq_num.SeqNum) : Result seq_num.SeqNum := do
  ok self

/-- Trait implementation: [framed_channel::seq_num::{impl core::clone::Clone for framed_channel::seq_num::SeqNum}]
    Source: 'src/seq_num.rs', lines 34:16-34:21 -/
@[reducible]
def seq_num.SeqNum.Insts.CoreCloneClone : core.clone.Clone seq_num.SeqNum := {
  clone := seq_num.SeqNum.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [framed_channel::seq_num::{impl core::marker::Copy for framed_channel::seq_num::SeqNum}]
    Source: 'src/seq_num.rs', lines 34:23-34:27 -/
@[reducible]
def seq_num.SeqNum.Insts.CoreMarkerCopy : core.marker.Copy seq_num.SeqNum := {
  cloneInst := seq_num.SeqNum.Insts.CoreCloneClone
}

/-- Trait implementation: [framed_channel::seq_num::{impl core::marker::StructuralPartialEq for framed_channel::seq_num::SeqNum}]
    Source: 'src/seq_num.rs', lines 34:29-34:38 -/
@[reducible]
def seq_num.SeqNum.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq seq_num.SeqNum := {
}

/-- [framed_channel::seq_num::{impl core::cmp::PartialEq<framed_channel::seq_num::SeqNum> for framed_channel::seq_num::SeqNum}::eq]:
    Source: 'src/seq_num.rs', lines 34:29-34:38
    Visibility: public -/
def seq_num.SeqNum.Insts.CoreCmpPartialEqSeqNum.eq
  (self : seq_num.SeqNum) (other : seq_num.SeqNum) : Result Bool := do
  ok (self.value = other.value)

/-- Trait implementation: [framed_channel::seq_num::{impl core::cmp::PartialEq<framed_channel::seq_num::SeqNum> for framed_channel::seq_num::SeqNum}]
    Source: 'src/seq_num.rs', lines 34:29-34:38 -/
@[reducible]
def seq_num.SeqNum.Insts.CoreCmpPartialEqSeqNum : core.cmp.PartialEq
  seq_num.SeqNum seq_num.SeqNum := {
  eq := seq_num.SeqNum.Insts.CoreCmpPartialEqSeqNum.eq
}

/-- [framed_channel::seq_num::{impl core::cmp::Eq for framed_channel::seq_num::SeqNum}::assert_fields_are_eq]:
    Source: 'src/seq_num.rs', lines 34:40-34:42
    Visibility: public -/
def seq_num.SeqNum.Insts.CoreCmpEq.assert_fields_are_eq
  (self : seq_num.SeqNum) : Result Unit := do
  ok ()

/-- Trait implementation: [framed_channel::seq_num::{impl core::cmp::Eq for framed_channel::seq_num::SeqNum}]
    Source: 'src/seq_num.rs', lines 34:40-34:42 -/
@[reducible]
def seq_num.SeqNum.Insts.CoreCmpEq : core.cmp.Eq seq_num.SeqNum := {
  partialEqInst := seq_num.SeqNum.Insts.CoreCmpPartialEqSeqNum
  assert_fields_are_eq := seq_num.SeqNum.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [framed_channel::seq_num::{framed_channel::seq_num::SeqNum}::new]:
    Source: 'src/seq_num.rs', lines 42:4-44:5
    Visibility: public -/
def seq_num.SeqNum.new (value : Std.U16) : Result seq_num.SeqNum := do
  ok { value }

/-- [framed_channel::seq_num::{framed_channel::seq_num::SeqNum}::get]:
    Source: 'src/seq_num.rs', lines 48:4-50:5
    Visibility: public -/
def seq_num.SeqNum.get (self : seq_num.SeqNum) : Result Std.U16 := do
  ok self.value

/-- [framed_channel::seq_num::{framed_channel::seq_num::SeqNum}::succ]:
    Source: 'src/seq_num.rs', lines 54:4-56:5
    Visibility: public -/
def seq_num.SeqNum.succ (self : seq_num.SeqNum) : Result seq_num.SeqNum := do
  let i ← lift (core.num.U16.wrapping_add self.value 1#u16)
  ok { value := i }

/-- [framed_channel::seq_num::{framed_channel::seq_num::SeqNum}::add]:
    Source: 'src/seq_num.rs', lines 67:4-69:5
    Visibility: public -/
def seq_num.SeqNum.add
  (self : seq_num.SeqNum) (n : Std.U16) : Result seq_num.SeqNum := do
  let i ← lift (core.num.U16.wrapping_add self.value n)
  ok { value := i }

/-- [framed_channel::seq_num::{framed_channel::seq_num::SeqNum}::dist]:
    Source: 'src/seq_num.rs', lines 74:4-76:5
    Visibility: public -/
def seq_num.SeqNum.dist
  (self : seq_num.SeqNum) (other : seq_num.SeqNum) : Result Std.U16 := do
  ok (core.num.U16.wrapping_sub other.value self.value)

/-- [framed_channel::seq_num::{framed_channel::seq_num::SeqNum}::lt]:
    Source: 'src/seq_num.rs', lines 82:4-85:5
    Visibility: public -/
def seq_num.SeqNum.lt
  (self : seq_num.SeqNum) (other : seq_num.SeqNum) : Result Bool := do
  let d ← lift (core.num.U16.wrapping_sub other.value self.value)
  if d != 0#u16
  then ok (d < seq_num.HALF)
  else ok false

/-- [framed_channel::stuff::MARKER]
    Source: 'src/stuff.rs', lines 19:0-19:28
    Visibility: public -/
@[global_simps, irreducible] def stuff.MARKER : Std.U8 := 126#u8

/-- [framed_channel::stuff::ESC]
    Source: 'src/stuff.rs', lines 22:0-22:25
    Visibility: public -/
@[global_simps, irreducible] def stuff.ESC : Std.U8 := 125#u8

/-- [framed_channel::stuff::XOR_MASK]
    Source: 'src/stuff.rs', lines 26:0-26:30
    Visibility: public -/
@[global_simps, irreducible] def stuff.XOR_MASK : Std.U8 := 32#u8

/-- [framed_channel::stuff::{impl core::fmt::Debug for framed_channel::stuff::UnstuffError}::fmt]:
    Source: 'src/stuff.rs', lines 29:9-29:14
    Visibility: public -/
def stuff.UnstuffError.Insts.CoreFmtDebug.fmt
  (self : stuff.UnstuffError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | stuff.UnstuffError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")
  | stuff.UnstuffError.BadEscape =>
    core.fmt.Formatter.write_str f (toStr "BadEscape")

/-- Trait implementation: [framed_channel::stuff::{impl core::fmt::Debug for framed_channel::stuff::UnstuffError}]
    Source: 'src/stuff.rs', lines 29:9-29:14 -/
@[reducible]
def stuff.UnstuffError.Insts.CoreFmtDebug : core.fmt.Debug stuff.UnstuffError
  := {
  fmt := stuff.UnstuffError.Insts.CoreFmtDebug.fmt
}

/-- [framed_channel::stuff::{impl core::clone::Clone for framed_channel::stuff::UnstuffError}::clone]:
    Source: 'src/stuff.rs', lines 29:16-29:21
    Visibility: public -/
def stuff.UnstuffError.Insts.CoreCloneClone.clone
  (self : stuff.UnstuffError) : Result stuff.UnstuffError := do
  ok self

/-- Trait implementation: [framed_channel::stuff::{impl core::clone::Clone for framed_channel::stuff::UnstuffError}]
    Source: 'src/stuff.rs', lines 29:16-29:21 -/
@[reducible]
def stuff.UnstuffError.Insts.CoreCloneClone : core.clone.Clone
  stuff.UnstuffError := {
  clone := stuff.UnstuffError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [framed_channel::stuff::{impl core::marker::Copy for framed_channel::stuff::UnstuffError}]
    Source: 'src/stuff.rs', lines 29:23-29:27 -/
@[reducible]
def stuff.UnstuffError.Insts.CoreMarkerCopy : core.marker.Copy
  stuff.UnstuffError := {
  cloneInst := stuff.UnstuffError.Insts.CoreCloneClone
}

/-- Trait implementation: [framed_channel::stuff::{impl core::marker::StructuralPartialEq for framed_channel::stuff::UnstuffError}]
    Source: 'src/stuff.rs', lines 29:29-29:38 -/
@[reducible]
def stuff.UnstuffError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq stuff.UnstuffError := {
}

/-- [framed_channel::stuff::{impl core::cmp::PartialEq<framed_channel::stuff::UnstuffError> for framed_channel::stuff::UnstuffError}::eq]:
    Source: 'src/stuff.rs', lines 29:29-29:38
    Visibility: public -/
def stuff.UnstuffError.Insts.CoreCmpPartialEqUnstuffError.eq
  (self : stuff.UnstuffError) (other : stuff.UnstuffError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [framed_channel::stuff::{impl core::cmp::PartialEq<framed_channel::stuff::UnstuffError> for framed_channel::stuff::UnstuffError}]
    Source: 'src/stuff.rs', lines 29:29-29:38 -/
@[reducible]
def stuff.UnstuffError.Insts.CoreCmpPartialEqUnstuffError : core.cmp.PartialEq
  stuff.UnstuffError stuff.UnstuffError := {
  eq := stuff.UnstuffError.Insts.CoreCmpPartialEqUnstuffError.eq
}

/-- Trait implementation: [framed_channel::stuff::{impl core::cmp::Eq for framed_channel::stuff::UnstuffError}]
    Source: 'src/stuff.rs', lines 29:40-29:42 -/
@[reducible]
impl_def stuff.UnstuffError.Insts.CoreCmpEq : core.cmp.Eq stuff.UnstuffError
  := {
  partialEqInst := stuff.UnstuffError.Insts.CoreCmpPartialEqUnstuffError
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    stuff.UnstuffError.Insts.CoreCmpEq
}

/-- [framed_channel::stuff::stuff]: loop body 0:
    Source: 'src/stuff.rs', lines 45:4-58:1
    Visibility: public -/
@[rust_loop_body]
def stuff.stuff_loop.body
  (payload : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len payload
  if i < i1
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8)
        payload i
    match o with
    | none => ok (done out)
    | some b =>
      let out1 ←
        if b = stuff.MARKER
        then
          do
          let out2 ← alloc.vec.Vec.push out stuff.ESC
          let i2 ← lift (b ^^^ stuff.XOR_MASK)
          alloc.vec.Vec.push out2 i2
        else
          if b = stuff.ESC
          then
            do
            let out2 ← alloc.vec.Vec.push out stuff.ESC
            let i2 ← lift (b ^^^ stuff.XOR_MASK)
            alloc.vec.Vec.push out2 i2
          else alloc.vec.Vec.push out b
      let i2 ← i + 1#usize
      ok (cont (out1, i2))
  else ok (done out)

/-- [framed_channel::stuff::stuff]: loop 0:
    Source: 'src/stuff.rs', lines 45:4-58:1
    Visibility: public -/
@[rust_loop]
def stuff.stuff_loop
  (payload : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => stuff.stuff_loop.body payload out1 i1)
    (out, i)

/-- [framed_channel::stuff::stuff]:
    Source: 'src/stuff.rs', lines 43:0-58:1
    Visibility: public -/
@[reducible]
def stuff.stuff
  (payload : Slice Std.U8) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  stuff.stuff_loop payload out 0#usize

/-- [framed_channel::stuff::encode_frame]:
    Source: 'src/stuff.rs', lines 64:0-67:1
    Visibility: public -/
def stuff.encode_frame
  (payload : Slice Std.U8) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let out1 ← stuff.stuff payload out
  alloc.vec.Vec.push out1 stuff.MARKER

/-- [framed_channel::stuff::unstuff]: loop body 0:
    Source: 'src/stuff.rs', lines 80:4-104:1
    Visibility: public -/
@[rust_loop_body]
def stuff.unstuff_loop.body
  (wire : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (core.result.Result
    ((alloc.vec.Vec Std.U8) × Std.Usize) stuff.UnstuffError))
  := do
  let i1 := Slice.len wire
  if i < i1
  then
    let o ←
      core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8) wire
        i
    match o with
    | none => ok (done (core.result.Result.Err stuff.UnstuffError.Truncated))
    | some b =>
      if b = stuff.MARKER
      then let i2 ← i + 1#usize
           ok (done (core.result.Result.Ok (out, i2)))
      else
        if b = stuff.ESC
        then
          let i2 ← i + 1#usize
          let o1 ←
            core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8)
              wire i2
          match o1 with
          | none =>
            ok (done (core.result.Result.Err stuff.UnstuffError.Truncated))
          | some c =>
            let i3 ← lift (stuff.MARKER ^^^ stuff.XOR_MASK)
            if c != i3
            then
              let i4 ← lift (stuff.ESC ^^^ stuff.XOR_MASK)
              if c != i4
              then
                ok (done (core.result.Result.Err stuff.UnstuffError.BadEscape))
              else
                let i5 ← lift (c ^^^ stuff.XOR_MASK)
                let out1 ← alloc.vec.Vec.push out i5
                let i6 ← i + 2#usize
                ok (cont (out1, i6))
            else
              let i4 ← lift (c ^^^ stuff.XOR_MASK)
              let out1 ← alloc.vec.Vec.push out i4
              let i5 ← i + 2#usize
              ok (cont (out1, i5))
        else
          let out1 ← alloc.vec.Vec.push out b
          let i2 ← i + 1#usize
          ok (cont (out1, i2))
  else ok (done (core.result.Result.Err stuff.UnstuffError.Truncated))

/-- [framed_channel::stuff::unstuff]: loop 0:
    Source: 'src/stuff.rs', lines 80:4-104:1
    Visibility: public -/
@[rust_loop]
def stuff.unstuff_loop
  (wire : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (core.result.Result ((alloc.vec.Vec Std.U8) × Std.Usize)
    stuff.UnstuffError)
  := do
  loop
    (fun (out1, i1) => stuff.unstuff_loop.body wire out1 i1)
    (out, i)

/-- [framed_channel::stuff::unstuff]:
    Source: 'src/stuff.rs', lines 77:0-104:1
    Visibility: public -/
@[reducible]
def stuff.unstuff
  (wire : Slice Std.U8) :
  Result (core.result.Result ((alloc.vec.Vec Std.U8) × Std.Usize)
    stuff.UnstuffError)
  := do
  stuff.unstuff_loop wire (alloc.vec.Vec.new Std.U8) 0#usize

/-- [framed_channel::varint::{impl core::fmt::Debug for framed_channel::varint::VarintError}::fmt]:
    Source: 'src/varint.rs', lines 8:9-8:14
    Visibility: public -/
def varint.VarintError.Insts.CoreFmtDebug.fmt
  (self : varint.VarintError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | varint.VarintError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")
  | varint.VarintError.Overlong =>
    core.fmt.Formatter.write_str f (toStr "Overlong")

/-- Trait implementation: [framed_channel::varint::{impl core::fmt::Debug for framed_channel::varint::VarintError}]
    Source: 'src/varint.rs', lines 8:9-8:14 -/
@[reducible]
def varint.VarintError.Insts.CoreFmtDebug : core.fmt.Debug varint.VarintError
  := {
  fmt := varint.VarintError.Insts.CoreFmtDebug.fmt
}

/-- [framed_channel::varint::{impl core::clone::Clone for framed_channel::varint::VarintError}::clone]:
    Source: 'src/varint.rs', lines 8:16-8:21
    Visibility: public -/
def varint.VarintError.Insts.CoreCloneClone.clone
  (self : varint.VarintError) : Result varint.VarintError := do
  ok self

/-- Trait implementation: [framed_channel::varint::{impl core::clone::Clone for framed_channel::varint::VarintError}]
    Source: 'src/varint.rs', lines 8:16-8:21 -/
@[reducible]
def varint.VarintError.Insts.CoreCloneClone : core.clone.Clone
  varint.VarintError := {
  clone := varint.VarintError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [framed_channel::varint::{impl core::marker::Copy for framed_channel::varint::VarintError}]
    Source: 'src/varint.rs', lines 8:23-8:27 -/
@[reducible]
def varint.VarintError.Insts.CoreMarkerCopy : core.marker.Copy
  varint.VarintError := {
  cloneInst := varint.VarintError.Insts.CoreCloneClone
}

/-- Trait implementation: [framed_channel::varint::{impl core::marker::StructuralPartialEq for framed_channel::varint::VarintError}]
    Source: 'src/varint.rs', lines 8:29-8:38 -/
@[reducible]
def varint.VarintError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq varint.VarintError := {
}

/-- [framed_channel::varint::{impl core::cmp::PartialEq<framed_channel::varint::VarintError> for framed_channel::varint::VarintError}::eq]:
    Source: 'src/varint.rs', lines 8:29-8:38
    Visibility: public -/
def varint.VarintError.Insts.CoreCmpPartialEqVarintError.eq
  (self : varint.VarintError) (other : varint.VarintError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [framed_channel::varint::{impl core::cmp::PartialEq<framed_channel::varint::VarintError> for framed_channel::varint::VarintError}]
    Source: 'src/varint.rs', lines 8:29-8:38 -/
@[reducible]
def varint.VarintError.Insts.CoreCmpPartialEqVarintError : core.cmp.PartialEq
  varint.VarintError varint.VarintError := {
  eq := varint.VarintError.Insts.CoreCmpPartialEqVarintError.eq
}

/-- Trait implementation: [framed_channel::varint::{impl core::cmp::Eq for framed_channel::varint::VarintError}]
    Source: 'src/varint.rs', lines 8:40-8:42 -/
@[reducible]
impl_def varint.VarintError.Insts.CoreCmpEq : core.cmp.Eq varint.VarintError
  := {
  partialEqInst := varint.VarintError.Insts.CoreCmpPartialEqVarintError
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    varint.VarintError.Insts.CoreCmpEq
}

/-- [framed_channel::zigzag::zigzag]:
    Source: 'src/zigzag.rs', lines 16:0-18:1
    Visibility: public -/
def zigzag.zigzag (n : Std.I32) : Result Std.U32 := do
  let i ← n <<< 1#i32
  let i1 ← n >>> 31#i32
  let i2 ← lift (i ^^^ i1)
  ok (IScalar.hcast .U32 i2)

/-- [framed_channel::zigzag::unzigzag]:
    Source: 'src/zigzag.rs', lines 21:0-28:1
    Visibility: public -/
def zigzag.unzigzag (m : Std.U32) : Result Std.I32 := do
  let i ← m >>> 1#i32
  let half ← lift (UScalar.hcast .I32 i)
  let i1 ← lift (m &&& 1#u32)
  if i1 = 0#u32
  then ok half
  else ok (~~~ half)

/-- [framed_channel::zigzag::encode_i32]:
    Source: 'src/zigzag.rs', lines 31:0-33:1
    Visibility: public -/
def zigzag.encode_i32
  (n : Std.I32) (out : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let i ← zigzag.zigzag n
  varint.encode_u32 i out

/-- [framed_channel::zigzag::decode_i32]:
    Source: 'src/zigzag.rs', lines 44:0-49:1
    Visibility: public -/
def zigzag.decode_i32
  (bytes : Slice Std.U8) :
  Result (core.result.Result (Std.I32 × Std.Usize) varint.VarintError)
  := do
  let r ← varint.decode_u32 bytes
  match r with
  | core.result.Result.Ok p =>
    let (m, k) := p
    let i ← zigzag.unzigzag m
    ok (core.result.Result.Ok (i, k))
  | core.result.Result.Err e => ok (core.result.Result.Err e)

end framed_channel
