-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [framed_channel]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace framed_channel

/-- [framed_channel::channel::DeliverFail]
    Source: 'src/channel.rs', lines 38:0-38:23
    Visibility: public -/
@[reducible]
def channel.DeliverFail := Unit

/-- [framed_channel::channel::SendFail]
    Source: 'src/channel.rs', lines 45:0-45:20
    Visibility: public -/
@[reducible]
def channel.SendFail := Unit

/-- [framed_channel::varint::VarintError]
    Source: 'src/varint.rs', lines 9:0-14:1
    Visibility: public -/
@[discriminant isize]
inductive varint.VarintError where
| Truncated : varint.VarintError
| Overlong : varint.VarintError

/-- [framed_channel::channel::Channel]
    Source: 'src/channel.rs', lines 97:0-101:1
    Visibility: public -/
structure channel.Channel (Q : Type) where
  out : Q
  wire : alloc.vec.Vec Std.U8
  in_flight : Std.Usize

/-- [framed_channel::ring_buffer::RingBuffer]
    Source: 'src/ring_buffer.rs', lines 23:0-28:1
    Visibility: public -/
structure ring_buffer.RingBuffer (T : Type) where
  buf : alloc.vec.Vec T
  head : Std.Usize
  tail : Std.Usize
  len : Std.Usize

/-- [framed_channel::ring_buffer::Full]
    Source: 'src/ring_buffer.rs', lines 18:0-18:16
    Visibility: public -/
@[reducible]
def ring_buffer.Full := Unit

/-- Trait declaration: [framed_channel::queue::BoundedQueue]
    Source: 'src/queue.rs', lines 16:0-48:1
    Visibility: public -/
structure queue.BoundedQueue (Self : Type) (T : Type) where
  with_capacity : Std.Usize → Result Self
  capacity : Self → Result Std.Usize
  len : Self → Result Std.Usize
  is_empty : Self → Result Bool
  is_full : Self → Result Bool
  push : Self → T → Result ((core.result.Result Unit ring_buffer.Full) ×
    Self)
  pop : Self → Result ((Option T) × Self)
  contents : Self → Result (alloc.vec.Vec T)

/-- [framed_channel::queue::VecQueue]
    Source: 'src/queue.rs', lines 54:0-57:1
    Visibility: public -/
structure queue.VecQueue (T : Type) where
  items : alloc.vec.Vec T
  cap : Std.Usize

/-- [framed_channel::stuff::UnstuffError]
    Source: 'src/stuff.rs', lines 30:0-36:1
    Visibility: public -/
@[discriminant isize]
inductive stuff.UnstuffError where
| Truncated : stuff.UnstuffError
| BadEscape : stuff.UnstuffError

end framed_channel
