#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# tests/spdx/run.sh -- fixture tests for check-spdx.sh.
#
# Each case builds a small --root tree under a temporary directory (not a git work tree, so the
# `find` enumeration is exercised) and checks the exit status and the file the output names.
#
# Usage: bash tests/spdx/run.sh [-h | --help]      (from any directory)
# Requires: bash >= 4.4.
# Exit: 0 every case behaves as recorded, 1 otherwise, 2 usage error.

set -u

case "${1:-}" in
  "") ;;
  -h|--help) awk 'NR > 2 && !/^#/ { exit } NR > 2 { sub(/^# ?/, ""); print }' "$0"; exit 0 ;;
  *) echo "run.sh: unknown argument '$1' (try --help)" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EX="$(cd "$HERE/../.." && pwd)"
CHECK="$EX/scripts/check-spdx.sh"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

failures=0
case_num=0

# base_tree DIR -- a minimal, fully-passing tree: LICENSE, NOTICE, a shell script with its header
# on line 2 after the shebang, a headered Lean file, and both Aeneas-generated exclusions with
# their banner and no header.
base_tree() {
  local d="$1"
  mkdir -p "$d/framed_channel/aeneas/FramedChannelAeneas/Extracted" "$d/.githooks"
  printf 'Apache License text (fixture, not the real one)\n' > "$d/LICENSE"
  printf 'Fixture NOTICE\n' > "$d/NOTICE"
  printf '#!/usr/bin/env bash\n# SPDX-License-Identifier: Apache-2.0\n# foo.sh -- fixture.\n' \
    > "$d/framed_channel/foo.sh"
  printf '#!/usr/bin/env bash\n# SPDX-License-Identifier: Apache-2.0\n# pre-push -- fixture.\n' \
    > "$d/.githooks/pre-push"
  printf -- '-- SPDX-License-Identifier: Apache-2.0\nimport Foo\n' > "$d/framed_channel/bar.lean"
  printf -- '-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS\n-- [fixture]: type definitions\n' \
    > "$d/framed_channel/aeneas/FramedChannelAeneas/Extracted/Types.lean"
  printf -- '-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS\n-- [fixture]: function definitions\n' \
    > "$d/framed_channel/aeneas/FramedChannelAeneas/Extracted/Funs.lean"
}

run_case() {
  # run_case NAME ROOT WANT_RC WANT_TEXT
  local name="$1" root="$2" want_rc="$3" want_text="$4"
  case_num=$((case_num + 1))
  local out rc
  out="$(bash "$CHECK" --root "$root" 2>&1)"
  rc=$?
  if [ "$rc" -eq "$want_rc" ] && { [ -z "$want_text" ] || grep -qF -- "$want_text" <<< "$out"; }; then
    echo "[ok] $name (exit $rc)"
  else
    echo "[FAIL] $name: exit $rc (expected $want_rc)$( [ -n "$want_text" ] && echo ", text '$want_text' $(grep -qF -- "$want_text" <<< "$out" && echo found || echo missing)" )"
    sed 's/^/    /' <<< "$out"
    failures=$((failures + 1))
  fi
}

# 1. all headers present
d1="$work/case1"; base_tree "$d1"
run_case "all headers present; exclusions and a line-2 header accepted" "$d1" 0 "[ok] license headers"

# 2. one .lean missing its header
d2="$work/case2"; base_tree "$d2"
printf 'import Baz\n' > "$d2/framed_channel/baz.lean"
run_case "one .lean missing" "$d2" 1 "framed_channel/baz.lean: no SPDX-License-Identifier"

# 3. a generated file without its banner (signals a hand edit)
d3="$work/case3"; base_tree "$d3"
printf -- '-- hand-edited, banner removed\nimport Aeneas\n' \
  > "$d3/framed_channel/aeneas/FramedChannelAeneas/Extracted/Types.lean"
run_case "generated file without its banner" "$d3" 1 \
  "Extracted/Types.lean: generated file has lost its generator banner"

# 4. a file under .lake/ without a header (pruned entirely, never scanned)
d4="$work/case4"; base_tree "$d4"
mkdir -p "$d4/framed_channel/aeneas/.lake"
printf 'import Unheadered\n' > "$d4/framed_channel/aeneas/.lake/generated.lean"
run_case "file under .lake/ without a header" "$d4" 0 "[ok] license headers"

# 5. NOTICE absent
d5="$work/case5"; base_tree "$d5"
rm -f "$d5/NOTICE"
run_case "NOTICE absent" "$d5" 1 "NOTICE: missing at the repository root"

# 6. an extensionless file under .githooks/ missing its header (git hooks cannot carry an
# extension, so this path is covered by name, not by the extension list).
d6="$work/case6"; base_tree "$d6"
printf '#!/usr/bin/env bash\necho no header here\n' > "$d6/.githooks/pre-push"
run_case ".githooks/pre-push missing its header" "$d6" 1 \
  ".githooks/pre-push: no SPDX-License-Identifier"

if [ $failures -ne 0 ]; then
  echo "tests/spdx: $failures of $case_num case(s) failed"
  exit 1
fi
echo "tests/spdx: all $case_num cases pass"
